// @generated by protobuf-ts 2.11.1 with parameter long_type_number
// @generated from protobuf file "hypurr/ios.proto" (package "hypurr", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { IosService } from "./ios";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { PortfolioSummaryResponse } from "./ios";
import type { PortfolioSummaryRequest } from "./ios";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service hypurr.IosService
 */
export interface IIosServiceClient {
    /**
     * @generated from protobuf rpc: PortfolioSummary
     */
    portfolioSummary(input: PortfolioSummaryRequest, options?: RpcOptions): UnaryCall<PortfolioSummaryRequest, PortfolioSummaryResponse>;
}
/**
 * @generated from protobuf service hypurr.IosService
 */
export class IosServiceClient implements IIosServiceClient, ServiceInfo {
    typeName = IosService.typeName;
    methods = IosService.methods;
    options = IosService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: PortfolioSummary
     */
    portfolioSummary(input: PortfolioSummaryRequest, options?: RpcOptions): UnaryCall<PortfolioSummaryRequest, PortfolioSummaryResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<PortfolioSummaryRequest, PortfolioSummaryResponse>("unary", this._transport, method, opt, input);
    }
}
