syntax = "proto3";
package hypurr;
option go_package = "gitlab.com/hypurr/hypurr-grpc/go/hypurr/telegram";

import "google/protobuf/wrappers.proto";

import "hypurr/tools.proto";
import "hypurr/wallet.proto";
import "hypurr/user.proto";
import "hypurr/launch.proto";
import "hypurr/common.proto";
import "hypurr/hpumpv1.proto";
import "hypurr/trade.proto";
import "hypurr/cabal.proto";


// Auth endpoints
message TelegramUserRequest {
  map<string, string> auth_data = 1;
}

message TelegramUserResponse {
  TelegramUser user = 1;
}

message TelegramUserWalletsRequest {
  map<string, string> auth_data = 1;
}

message TelegramUserWalletsResponse {
  repeated HyperliquidWallet wallets = 1;
}

message HyperliquidCoreTradeRequest {
  map<string, string> auth_data = 1;
  int64 wallet_id = 2;
  HyperliquidCoreOrder order = 3;
}

message HyperliquidCoreTradeResponse {
  double base_amount = 1;
  double quote_amount = 2;
  string message = 3;
  bool success = 4;
}

message HyperliquidCoreCancelOrdersRequest {
  map<string, string> auth_data = 1;
  int64 wallet_id = 2;
  repeated HyperliquidCoreCancel cancels = 3;
}

message HyperliquidCoreCancelOrdersResponse {
  repeated HyperliquidCoreOrderCanceledStatus statuses = 1;
}

message HyperliquidTwapCreateRequest {
  map<string, string> auth_data = 1;
  int64 wallet_id = 2;
  int64 duration = 3;
  bool buy = 4;
  bool use_chasing = 5;
  bool reduce_only = 6;
  google.protobuf.Int64Value spot_pair_id = 7;
  google.protobuf.Int64Value perp_pair_id = 8;
  google.protobuf.DoubleValue target_notional = 9;
  google.protobuf.DoubleValue target_quantity = 10;
  google.protobuf.DoubleValue target_leverage = 11;
  google.protobuf.DoubleValue min_price = 12;
  google.protobuf.DoubleValue max_price = 13;
}

message HyperliquidTwapCreateResponse {
  HyperliquidWalletTwapSession session = 1;
}

message HyperliquidTwapModifyRequest {
  map<string, string> auth_data = 1;
  int64 wallet_id = 2;
  int64 session_id = 3;
  google.protobuf.DoubleValue target_notional = 4;
  google.protobuf.DoubleValue target_quantity = 5;
  google.protobuf.DoubleValue target_leverage = 6;
  google.protobuf.DoubleValue min_price = 7;
  google.protobuf.DoubleValue max_price = 8;
}

message HyperliquidTwapModifyResponse {
  HyperliquidWalletTwapSession session = 1;
}

message HyperliquidTwapCancelRequest {
  map<string, string> auth_data = 1;
  int64 wallet_id = 2;
  int64 twap_session_id = 3;
}

message HyperliquidTwapCancelResponse {
}

message HyperliquidScaleCreateRequest {
  map<string, string> auth_data = 1;
  int64 wallet_id = 2;
  int64 order_count = 3;
  bool buy = 4;
  google.protobuf.Int64Value spot_pair_id = 5;
  google.protobuf.Int64Value perp_pair_id = 6;
  google.protobuf.DoubleValue target_notional = 7;
  google.protobuf.DoubleValue target_quantity = 8;
  google.protobuf.DoubleValue target_leverage = 9;
  google.protobuf.DoubleValue min_price = 10;
  google.protobuf.DoubleValue max_price = 11;
}

message HyperliquidScaleCreateResponse {
  HyperliquidWalletScaleSession session = 1;
}

message HyperliquidScaleCancelRequest {
  map<string, string> auth_data = 1;
  int64 wallet_id = 2;
  int64 scale_session_id = 3;
}

message HyperliquidScaleCancelResponse {
}

message HyperliquidLaunchTradeRequest {
  map<string, string> auth_data = 1;
  int64 launch_id = 2;
  int64 wallet_id = 3;
  TradeDirection direction = 4;
  double amount = 5;
}

message HyperliquidLaunchTradeResponse {
  double base_amount = 1;
  double quote_amount = 2;
  string message = 3;
  bool success = 4;
}

message HyperliquidSpotTradeRequest {
  map<string, string> auth_data = 1;
  int64 pair_id = 2;
  int64 wallet_id = 3;
  TradeDirection direction = 4;
  double amount = 5;
}

message HpumpV1LaunchTradeRequest {
  map<string, string> auth_data = 1;
  int64 launch_id = 2;
  int64 wallet_id = 3;
  TradeDirection direction = 4;
  string amount = 5;
  double max_slippage = 6;
  double max_gas_cost_usd = 7;
}

message HpumpV1LaunchTradeResponse {
  string base_amount = 1;
  string quote_amount = 2;
  string message = 3;
  bool success = 4;
}

message HyperliquidSpotTradeResponse {
  double base_amount = 1;
  double quote_amount = 2;
  string message = 3;
  bool success = 4;
}

message HyperliquidSpotSniperConfigsRequest {
  map<string, string> auth_data = 1;
}

message HyperliquidSpotSniperConfigsResponse {
  repeated HyperliquidSpotSniperConfig configs = 1;
}

message DeleteHyperliquidSpotSniperConfigRequest {
  map<string, string> auth_data = 1;
  int64 config_id = 2;
}

message DeleteHyperliquidSpotSniperConfigResponse {
  bool success = 1;
}

message CreateHyperliquidSpotSniperConfigRequest {
  map<string, string> auth_data = 1;
  HyperliquidSpotSniperConfig config = 2;
}

message CreateHyperliquidSpotSniperConfigResponse {
  bool success = 1;
  HyperliquidSpotSniperConfig config = 2;
}

message UpdateHyperliquidSpotSniperConfigRequest {
  map<string, string> auth_data = 1;
  HyperliquidSpotSniperConfig config = 2;
}

message UpdateHyperliquidSpotSniperConfigResponse {
  bool success = 1;
}

message HyperliquidWalletSpotTwapSessionsRequest {
  map<string, string> auth_data = 1;
  int64 wallet_id = 2;
}

message HyperliquidWalletSpotTwapSessionsResponse {
  repeated HyperliquidWalletSpotTwapSession sessions = 1;
}

message HyperliquidWalletTwapSessionsRequest {
  map<string, string> auth_data = 1;
  int64 wallet_id = 2;
}

message HyperliquidWalletTwapSessionsResponse {
  repeated HyperliquidWalletTwapSession sessions = 1;
}

message HyperliquidWalletScaleSessionsRequest {
  map<string, string> auth_data = 1;
  int64 wallet_id = 2;
}

message HyperliquidWalletScaleSessionsResponse {
  repeated HyperliquidWalletScaleSession sessions = 1;
}

message LaunchHyperliquidLaunchRequest {
  map<string, string> auth_data = 1;
  int64 wallet_id = 2;
  string description = 3;
  string full_name = 4;
  string token_name = 5;
  bytes media = 6;
  MediaType media_type = 7;
  int64 dev_lockup_seconds = 8;
  double initial_purchase_notional = 9;
}

message LaunchHyperliquidLaunchResponse {
 HyperliquidLaunch launch = 1;
}

message LaunchHpumpV1LaunchRequest {
  map<string, string> auth_data = 1;
  int64 wallet_id = 2;
  string description = 3;
  string full_name = 4;
  string token_name = 5;
  bytes media = 6;
  MediaType media_type = 7;
  int64 dev_lockup_seconds = 8;
  double initial_purchase_notional = 9;
  string launch_factory = 10;
}

message LaunchHpumpV1LaunchResponse {
  HpumpV1Launch launch = 1;
}

message EditHyperliquidLaunchRequest {
  map<string, string> auth_data = 1;
  int64 launch_id = 2;
  string description = 3;
  string full_name = 4;
  google.protobuf.BytesValue media = 5;
  MediaType media_type = 6;
  int64 dev_lockup_seconds = 7;
}

message EditHyperliquidLaunchResponse {
  HyperliquidLaunch launch = 1;
}

message HfunCabalAlertsRequest {
  map<string, string> auth_data = 1;
}

message HfunCabalAlertsResponse {
  repeated HypurrFunCabalAlert alerts = 1;
}

message HfunCabalWalletLabelAddRequest {
  map<string, string> auth_data = 1;
  string wallet_address = 2;
  string wallet_label = 3;
}

message HfunCabalWalletLabelAddResponse {

}

message HfunCabalWalletLabelModifyRequest {
  map<string, string> auth_data = 1;
  string wallet_label_old = 2;
  string wallet_label_new = 3;
}

message HfunCabalWalletLabelModifyResponse {

}

message HfunCabalWalletLabelDeleteRequest {
  map<string, string> auth_data = 1;
  string wallet_label = 2;
}

message HfunCabalWalletLabelDeleteResponse {

}

message EIP712Signature {
  string agentAddress = 1;
  string agentName = 2;
  int64 nonce = 3;
  string signature = 4;
  int64 chain_id = 5;
}

message HyperliquidAgentSignatureCreateRequest {
  map<string, string> auth_data = 1;
  string address = 2;
}

message HyperliquidAgentSignatureCreateResponse {
  string agent = 1;
}

message HyperliquidAgentWalletCreateRequest {
  map<string, string> auth_data = 1;
  string name = 2;
  EIP712Signature signature = 3;
}

message HyperliquidAgentWalletCreateResponse {

}

service Telegram {
  rpc TelegramUser (TelegramUserRequest) returns (TelegramUserResponse) {}
  rpc TelegramUserWallets (TelegramUserWalletsRequest) returns (TelegramUserWalletsResponse) {}

  // Launch
  rpc HyperliquidLaunchTrade (HyperliquidLaunchTradeRequest) returns (HyperliquidLaunchTradeResponse) {}
  rpc LaunchHyperliquidLaunch (LaunchHyperliquidLaunchRequest) returns (LaunchHyperliquidLaunchResponse) {}
  rpc EditHyperliquidLaunch (EditHyperliquidLaunchRequest) returns (EditHyperliquidLaunchResponse) {}

  // HpumpV1
  rpc HpumpV1LaunchTrade (HpumpV1LaunchTradeRequest) returns (HpumpV1LaunchTradeResponse) {}
  rpc LaunchHpumpV1Launch (LaunchHpumpV1LaunchRequest) returns (LaunchHpumpV1LaunchResponse) {}

  // Spot
  rpc HyperliquidSpotTrade (HyperliquidSpotTradeRequest) returns (HyperliquidSpotTradeResponse) {}
  rpc HyperliquidCoreTrade (HyperliquidCoreTradeRequest) returns (HyperliquidCoreTradeResponse) {}
  rpc HyperliquidCoreCancelOrders (HyperliquidCoreCancelOrdersRequest) returns (HyperliquidCoreCancelOrdersResponse) {}

  // Sessions
  rpc HyperliquidWalletSpotTwapSessions (HyperliquidWalletSpotTwapSessionsRequest) returns (HyperliquidWalletSpotTwapSessionsResponse) {}
  rpc HyperliquidWalletTwapSessions (HyperliquidWalletTwapSessionsRequest) returns (HyperliquidWalletTwapSessionsResponse) {}
  rpc HyperliquidWalletScaleSessions (HyperliquidWalletScaleSessionsRequest) returns (HyperliquidWalletScaleSessionsResponse) {}

  rpc HyperliquidTwapCreate (HyperliquidTwapCreateRequest) returns (HyperliquidTwapCreateResponse) {}
  rpc HyperliquidTwapModify (HyperliquidTwapModifyRequest) returns (HyperliquidTwapModifyResponse) {}
  rpc HyperliquidTwapCancel (HyperliquidTwapCancelRequest) returns (HyperliquidTwapCancelResponse) {}
  rpc HyperliquidScaleCreate (HyperliquidScaleCreateRequest) returns (HyperliquidScaleCreateResponse) {}
  rpc HyperliquidScaleCancel (HyperliquidScaleCancelRequest) returns (HyperliquidScaleCancelResponse) {}

  rpc HyperliquidSpotSniperConfigs (HyperliquidSpotSniperConfigsRequest) returns (HyperliquidSpotSniperConfigsResponse) {}
  rpc CreateHyperliquidSpotSniperConfig (CreateHyperliquidSpotSniperConfigRequest) returns (CreateHyperliquidSpotSniperConfigResponse) {}
  rpc DeleteHyperliquidSpotSniperConfig (DeleteHyperliquidSpotSniperConfigRequest) returns (DeleteHyperliquidSpotSniperConfigResponse) {}
  rpc UpdateHyperliquidSpotSniperConfig (UpdateHyperliquidSpotSniperConfigRequest) returns (UpdateHyperliquidSpotSniperConfigResponse) {}

  rpc HyperliquidAgentSignatureCreate (HyperliquidAgentSignatureCreateRequest) returns (HyperliquidAgentWalletCreateRequest) {}
  rpc HyperliquidAgentWalletCreate (HyperliquidAgentWalletCreateRequest) returns (HyperliquidAgentWalletCreateResponse) {}

  // Cabal
  rpc HfunCabalAlerts (HfunCabalAlertsRequest) returns (stream HfunCabalAlertsResponse) {}
  rpc HfunCabalWalletLabelAdd (HfunCabalWalletLabelAddRequest) returns (HfunCabalWalletLabelAddResponse) {}
  rpc HfunCabalWalletLabelModify (HfunCabalWalletLabelModifyRequest) returns (HfunCabalWalletLabelModifyResponse) {}
  rpc HfunCabalWalletLabelRemove (HfunCabalWalletLabelDeleteRequest) returns (HfunCabalWalletLabelDeleteResponse) {}
}
