// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.12
// source: hypurr/hypercore/hypercore_service.proto

package hypercore

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	HyperCore_WalletMovements_FullMethodName                   = "/hypercore.HyperCore/WalletMovements"
	HyperCore_WalletBalances_FullMethodName                    = "/hypercore.HyperCore/WalletBalances"
	HyperCore_AggregatedWalletPositioningStream_FullMethodName = "/hypercore.HyperCore/AggregatedWalletPositioningStream"
	HyperCore_AggregatedWalletLiquidations_FullMethodName      = "/hypercore.HyperCore/AggregatedWalletLiquidations"
	HyperCore_WalletBalancesStream_FullMethodName              = "/hypercore.HyperCore/WalletBalancesStream"
	HyperCore_WalletTradesStream_FullMethodName                = "/hypercore.HyperCore/WalletTradesStream"
	HyperCore_ValidatorDelegators_FullMethodName               = "/hypercore.HyperCore/ValidatorDelegators"
	HyperCore_ReferrerWallet_FullMethodName                    = "/hypercore.HyperCore/ReferrerWallet"
	HyperCore_WalletTags_FullMethodName                        = "/hypercore.HyperCore/WalletTags"
	HyperCore_WalletsByTag_FullMethodName                      = "/hypercore.HyperCore/WalletsByTag"
	HyperCore_WalletPerformance_FullMethodName                 = "/hypercore.HyperCore/WalletPerformance"
	HyperCore_WalletPerformanceSeries_FullMethodName           = "/hypercore.HyperCore/WalletPerformanceSeries"
	HyperCore_WalletPositioningSeries_FullMethodName           = "/hypercore.HyperCore/WalletPositioningSeries"
)

// HyperCoreClient is the client API for HyperCore service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HyperCoreClient interface {
	WalletMovements(ctx context.Context, in *WalletMovementsRequest, opts ...grpc.CallOption) (*WalletMovementsResponse, error)
	WalletBalances(ctx context.Context, in *WalletBalancesRequest, opts ...grpc.CallOption) (*WalletBalancesResponse, error)
	AggregatedWalletPositioningStream(ctx context.Context, in *AggregatedWalletPositioningStreamRequest, opts ...grpc.CallOption) (HyperCore_AggregatedWalletPositioningStreamClient, error)
	AggregatedWalletLiquidations(ctx context.Context, in *AggregatedWalletLiquidationsRequest, opts ...grpc.CallOption) (*AggregatedWalletLiquidationsResponse, error)
	WalletBalancesStream(ctx context.Context, opts ...grpc.CallOption) (HyperCore_WalletBalancesStreamClient, error)
	WalletTradesStream(ctx context.Context, in *WalletTradesStreamRequest, opts ...grpc.CallOption) (HyperCore_WalletTradesStreamClient, error)
	ValidatorDelegators(ctx context.Context, in *ValidatorDelegatorsRequest, opts ...grpc.CallOption) (*ValidatorDelegatorsResponse, error)
	ReferrerWallet(ctx context.Context, in *ReferrerWalletRequest, opts ...grpc.CallOption) (*ReferrerWalletResponse, error)
	WalletTags(ctx context.Context, in *WalletTagsRequest, opts ...grpc.CallOption) (*WalletTagsResponse, error)
	WalletsByTag(ctx context.Context, in *WalletsByTagRequest, opts ...grpc.CallOption) (*WalletsByTagResponse, error)
	WalletPerformance(ctx context.Context, in *WalletPerformanceRequest, opts ...grpc.CallOption) (*WalletPerformanceResponse, error)
	WalletPerformanceSeries(ctx context.Context, in *WalletPerformanceSeriesRequest, opts ...grpc.CallOption) (*WalletPerformanceSeriesResponse, error)
	WalletPositioningSeries(ctx context.Context, in *WalletPositioningSeriesRequest, opts ...grpc.CallOption) (*WalletPositioningSeriesResponse, error)
}

type hyperCoreClient struct {
	cc grpc.ClientConnInterface
}

func NewHyperCoreClient(cc grpc.ClientConnInterface) HyperCoreClient {
	return &hyperCoreClient{cc}
}

func (c *hyperCoreClient) WalletMovements(ctx context.Context, in *WalletMovementsRequest, opts ...grpc.CallOption) (*WalletMovementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletMovementsResponse)
	err := c.cc.Invoke(ctx, HyperCore_WalletMovements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperCoreClient) WalletBalances(ctx context.Context, in *WalletBalancesRequest, opts ...grpc.CallOption) (*WalletBalancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletBalancesResponse)
	err := c.cc.Invoke(ctx, HyperCore_WalletBalances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperCoreClient) AggregatedWalletPositioningStream(ctx context.Context, in *AggregatedWalletPositioningStreamRequest, opts ...grpc.CallOption) (HyperCore_AggregatedWalletPositioningStreamClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HyperCore_ServiceDesc.Streams[0], HyperCore_AggregatedWalletPositioningStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &hyperCoreAggregatedWalletPositioningStreamClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HyperCore_AggregatedWalletPositioningStreamClient interface {
	Recv() (*AggregatedWalletPositioningStreamResponse, error)
	grpc.ClientStream
}

type hyperCoreAggregatedWalletPositioningStreamClient struct {
	grpc.ClientStream
}

func (x *hyperCoreAggregatedWalletPositioningStreamClient) Recv() (*AggregatedWalletPositioningStreamResponse, error) {
	m := new(AggregatedWalletPositioningStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hyperCoreClient) AggregatedWalletLiquidations(ctx context.Context, in *AggregatedWalletLiquidationsRequest, opts ...grpc.CallOption) (*AggregatedWalletLiquidationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AggregatedWalletLiquidationsResponse)
	err := c.cc.Invoke(ctx, HyperCore_AggregatedWalletLiquidations_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperCoreClient) WalletBalancesStream(ctx context.Context, opts ...grpc.CallOption) (HyperCore_WalletBalancesStreamClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HyperCore_ServiceDesc.Streams[1], HyperCore_WalletBalancesStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &hyperCoreWalletBalancesStreamClient{ClientStream: stream}
	return x, nil
}

type HyperCore_WalletBalancesStreamClient interface {
	Send(*WalletBalancesStreamRequest) error
	Recv() (*WalletBalancesStreamResponse, error)
	grpc.ClientStream
}

type hyperCoreWalletBalancesStreamClient struct {
	grpc.ClientStream
}

func (x *hyperCoreWalletBalancesStreamClient) Send(m *WalletBalancesStreamRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *hyperCoreWalletBalancesStreamClient) Recv() (*WalletBalancesStreamResponse, error) {
	m := new(WalletBalancesStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hyperCoreClient) WalletTradesStream(ctx context.Context, in *WalletTradesStreamRequest, opts ...grpc.CallOption) (HyperCore_WalletTradesStreamClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HyperCore_ServiceDesc.Streams[2], HyperCore_WalletTradesStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &hyperCoreWalletTradesStreamClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type HyperCore_WalletTradesStreamClient interface {
	Recv() (*WalletTradesStreamResponse, error)
	grpc.ClientStream
}

type hyperCoreWalletTradesStreamClient struct {
	grpc.ClientStream
}

func (x *hyperCoreWalletTradesStreamClient) Recv() (*WalletTradesStreamResponse, error) {
	m := new(WalletTradesStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *hyperCoreClient) ValidatorDelegators(ctx context.Context, in *ValidatorDelegatorsRequest, opts ...grpc.CallOption) (*ValidatorDelegatorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidatorDelegatorsResponse)
	err := c.cc.Invoke(ctx, HyperCore_ValidatorDelegators_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperCoreClient) ReferrerWallet(ctx context.Context, in *ReferrerWalletRequest, opts ...grpc.CallOption) (*ReferrerWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReferrerWalletResponse)
	err := c.cc.Invoke(ctx, HyperCore_ReferrerWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperCoreClient) WalletTags(ctx context.Context, in *WalletTagsRequest, opts ...grpc.CallOption) (*WalletTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletTagsResponse)
	err := c.cc.Invoke(ctx, HyperCore_WalletTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperCoreClient) WalletsByTag(ctx context.Context, in *WalletsByTagRequest, opts ...grpc.CallOption) (*WalletsByTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletsByTagResponse)
	err := c.cc.Invoke(ctx, HyperCore_WalletsByTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperCoreClient) WalletPerformance(ctx context.Context, in *WalletPerformanceRequest, opts ...grpc.CallOption) (*WalletPerformanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletPerformanceResponse)
	err := c.cc.Invoke(ctx, HyperCore_WalletPerformance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperCoreClient) WalletPerformanceSeries(ctx context.Context, in *WalletPerformanceSeriesRequest, opts ...grpc.CallOption) (*WalletPerformanceSeriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletPerformanceSeriesResponse)
	err := c.cc.Invoke(ctx, HyperCore_WalletPerformanceSeries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hyperCoreClient) WalletPositioningSeries(ctx context.Context, in *WalletPositioningSeriesRequest, opts ...grpc.CallOption) (*WalletPositioningSeriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletPositioningSeriesResponse)
	err := c.cc.Invoke(ctx, HyperCore_WalletPositioningSeries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HyperCoreServer is the server API for HyperCore service.
// All implementations must embed UnimplementedHyperCoreServer
// for forward compatibility
type HyperCoreServer interface {
	WalletMovements(context.Context, *WalletMovementsRequest) (*WalletMovementsResponse, error)
	WalletBalances(context.Context, *WalletBalancesRequest) (*WalletBalancesResponse, error)
	AggregatedWalletPositioningStream(*AggregatedWalletPositioningStreamRequest, HyperCore_AggregatedWalletPositioningStreamServer) error
	AggregatedWalletLiquidations(context.Context, *AggregatedWalletLiquidationsRequest) (*AggregatedWalletLiquidationsResponse, error)
	WalletBalancesStream(HyperCore_WalletBalancesStreamServer) error
	WalletTradesStream(*WalletTradesStreamRequest, HyperCore_WalletTradesStreamServer) error
	ValidatorDelegators(context.Context, *ValidatorDelegatorsRequest) (*ValidatorDelegatorsResponse, error)
	ReferrerWallet(context.Context, *ReferrerWalletRequest) (*ReferrerWalletResponse, error)
	WalletTags(context.Context, *WalletTagsRequest) (*WalletTagsResponse, error)
	WalletsByTag(context.Context, *WalletsByTagRequest) (*WalletsByTagResponse, error)
	WalletPerformance(context.Context, *WalletPerformanceRequest) (*WalletPerformanceResponse, error)
	WalletPerformanceSeries(context.Context, *WalletPerformanceSeriesRequest) (*WalletPerformanceSeriesResponse, error)
	WalletPositioningSeries(context.Context, *WalletPositioningSeriesRequest) (*WalletPositioningSeriesResponse, error)
	mustEmbedUnimplementedHyperCoreServer()
}

// UnimplementedHyperCoreServer must be embedded to have forward compatible implementations.
type UnimplementedHyperCoreServer struct {
}

func (UnimplementedHyperCoreServer) WalletMovements(context.Context, *WalletMovementsRequest) (*WalletMovementsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WalletMovements not implemented")
}
func (UnimplementedHyperCoreServer) WalletBalances(context.Context, *WalletBalancesRequest) (*WalletBalancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WalletBalances not implemented")
}
func (UnimplementedHyperCoreServer) AggregatedWalletPositioningStream(*AggregatedWalletPositioningStreamRequest, HyperCore_AggregatedWalletPositioningStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method AggregatedWalletPositioningStream not implemented")
}
func (UnimplementedHyperCoreServer) AggregatedWalletLiquidations(context.Context, *AggregatedWalletLiquidationsRequest) (*AggregatedWalletLiquidationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AggregatedWalletLiquidations not implemented")
}
func (UnimplementedHyperCoreServer) WalletBalancesStream(HyperCore_WalletBalancesStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method WalletBalancesStream not implemented")
}
func (UnimplementedHyperCoreServer) WalletTradesStream(*WalletTradesStreamRequest, HyperCore_WalletTradesStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method WalletTradesStream not implemented")
}
func (UnimplementedHyperCoreServer) ValidatorDelegators(context.Context, *ValidatorDelegatorsRequest) (*ValidatorDelegatorsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidatorDelegators not implemented")
}
func (UnimplementedHyperCoreServer) ReferrerWallet(context.Context, *ReferrerWalletRequest) (*ReferrerWalletResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReferrerWallet not implemented")
}
func (UnimplementedHyperCoreServer) WalletTags(context.Context, *WalletTagsRequest) (*WalletTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WalletTags not implemented")
}
func (UnimplementedHyperCoreServer) WalletsByTag(context.Context, *WalletsByTagRequest) (*WalletsByTagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WalletsByTag not implemented")
}
func (UnimplementedHyperCoreServer) WalletPerformance(context.Context, *WalletPerformanceRequest) (*WalletPerformanceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WalletPerformance not implemented")
}
func (UnimplementedHyperCoreServer) WalletPerformanceSeries(context.Context, *WalletPerformanceSeriesRequest) (*WalletPerformanceSeriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WalletPerformanceSeries not implemented")
}
func (UnimplementedHyperCoreServer) WalletPositioningSeries(context.Context, *WalletPositioningSeriesRequest) (*WalletPositioningSeriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WalletPositioningSeries not implemented")
}
func (UnimplementedHyperCoreServer) mustEmbedUnimplementedHyperCoreServer() {}

// UnsafeHyperCoreServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HyperCoreServer will
// result in compilation errors.
type UnsafeHyperCoreServer interface {
	mustEmbedUnimplementedHyperCoreServer()
}

func RegisterHyperCoreServer(s grpc.ServiceRegistrar, srv HyperCoreServer) {
	s.RegisterService(&HyperCore_ServiceDesc, srv)
}

func _HyperCore_WalletMovements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletMovementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperCoreServer).WalletMovements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HyperCore_WalletMovements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperCoreServer).WalletMovements(ctx, req.(*WalletMovementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperCore_WalletBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperCoreServer).WalletBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HyperCore_WalletBalances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperCoreServer).WalletBalances(ctx, req.(*WalletBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperCore_AggregatedWalletPositioningStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AggregatedWalletPositioningStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HyperCoreServer).AggregatedWalletPositioningStream(m, &hyperCoreAggregatedWalletPositioningStreamServer{ServerStream: stream})
}

type HyperCore_AggregatedWalletPositioningStreamServer interface {
	Send(*AggregatedWalletPositioningStreamResponse) error
	grpc.ServerStream
}

type hyperCoreAggregatedWalletPositioningStreamServer struct {
	grpc.ServerStream
}

func (x *hyperCoreAggregatedWalletPositioningStreamServer) Send(m *AggregatedWalletPositioningStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _HyperCore_AggregatedWalletLiquidations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregatedWalletLiquidationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperCoreServer).AggregatedWalletLiquidations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HyperCore_AggregatedWalletLiquidations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperCoreServer).AggregatedWalletLiquidations(ctx, req.(*AggregatedWalletLiquidationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperCore_WalletBalancesStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HyperCoreServer).WalletBalancesStream(&hyperCoreWalletBalancesStreamServer{ServerStream: stream})
}

type HyperCore_WalletBalancesStreamServer interface {
	Send(*WalletBalancesStreamResponse) error
	Recv() (*WalletBalancesStreamRequest, error)
	grpc.ServerStream
}

type hyperCoreWalletBalancesStreamServer struct {
	grpc.ServerStream
}

func (x *hyperCoreWalletBalancesStreamServer) Send(m *WalletBalancesStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *hyperCoreWalletBalancesStreamServer) Recv() (*WalletBalancesStreamRequest, error) {
	m := new(WalletBalancesStreamRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _HyperCore_WalletTradesStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WalletTradesStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(HyperCoreServer).WalletTradesStream(m, &hyperCoreWalletTradesStreamServer{ServerStream: stream})
}

type HyperCore_WalletTradesStreamServer interface {
	Send(*WalletTradesStreamResponse) error
	grpc.ServerStream
}

type hyperCoreWalletTradesStreamServer struct {
	grpc.ServerStream
}

func (x *hyperCoreWalletTradesStreamServer) Send(m *WalletTradesStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _HyperCore_ValidatorDelegators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidatorDelegatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperCoreServer).ValidatorDelegators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HyperCore_ValidatorDelegators_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperCoreServer).ValidatorDelegators(ctx, req.(*ValidatorDelegatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperCore_ReferrerWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReferrerWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperCoreServer).ReferrerWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HyperCore_ReferrerWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperCoreServer).ReferrerWallet(ctx, req.(*ReferrerWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperCore_WalletTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperCoreServer).WalletTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HyperCore_WalletTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperCoreServer).WalletTags(ctx, req.(*WalletTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperCore_WalletsByTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletsByTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperCoreServer).WalletsByTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HyperCore_WalletsByTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperCoreServer).WalletsByTag(ctx, req.(*WalletsByTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperCore_WalletPerformance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletPerformanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperCoreServer).WalletPerformance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HyperCore_WalletPerformance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperCoreServer).WalletPerformance(ctx, req.(*WalletPerformanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperCore_WalletPerformanceSeries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletPerformanceSeriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperCoreServer).WalletPerformanceSeries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HyperCore_WalletPerformanceSeries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperCoreServer).WalletPerformanceSeries(ctx, req.(*WalletPerformanceSeriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HyperCore_WalletPositioningSeries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletPositioningSeriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HyperCoreServer).WalletPositioningSeries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HyperCore_WalletPositioningSeries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HyperCoreServer).WalletPositioningSeries(ctx, req.(*WalletPositioningSeriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HyperCore_ServiceDesc is the grpc.ServiceDesc for HyperCore service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HyperCore_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hypercore.HyperCore",
	HandlerType: (*HyperCoreServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WalletMovements",
			Handler:    _HyperCore_WalletMovements_Handler,
		},
		{
			MethodName: "WalletBalances",
			Handler:    _HyperCore_WalletBalances_Handler,
		},
		{
			MethodName: "AggregatedWalletLiquidations",
			Handler:    _HyperCore_AggregatedWalletLiquidations_Handler,
		},
		{
			MethodName: "ValidatorDelegators",
			Handler:    _HyperCore_ValidatorDelegators_Handler,
		},
		{
			MethodName: "ReferrerWallet",
			Handler:    _HyperCore_ReferrerWallet_Handler,
		},
		{
			MethodName: "WalletTags",
			Handler:    _HyperCore_WalletTags_Handler,
		},
		{
			MethodName: "WalletsByTag",
			Handler:    _HyperCore_WalletsByTag_Handler,
		},
		{
			MethodName: "WalletPerformance",
			Handler:    _HyperCore_WalletPerformance_Handler,
		},
		{
			MethodName: "WalletPerformanceSeries",
			Handler:    _HyperCore_WalletPerformanceSeries_Handler,
		},
		{
			MethodName: "WalletPositioningSeries",
			Handler:    _HyperCore_WalletPositioningSeries_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AggregatedWalletPositioningStream",
			Handler:       _HyperCore_AggregatedWalletPositioningStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WalletBalancesStream",
			Handler:       _HyperCore_WalletBalancesStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "WalletTradesStream",
			Handler:       _HyperCore_WalletTradesStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hypurr/hypercore/hypercore_service.proto",
}
