// @generated by protobuf-ts 2.11.1 with parameter long_type_number
// @generated from protobuf file "hypurr/aconnect/aconnect_service.proto" (package "aconnect", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * Identifiers only. Credentials are resolved from hypurr's encrypted store.
 *
 * @generated from protobuf message aconnect.ExecutionAccount
 */
export interface ExecutionAccount {
    /**
     * @generated from protobuf field: int64 exchange_account_id = 2
     */
    exchangeAccountId: number;
}
/**
 * @generated from protobuf message aconnect.PlaceOrderRequest
 */
export interface PlaceOrderRequest {
    /**
     * @generated from protobuf field: aconnect.ExecutionAccount account = 1
     */
    account?: ExecutionAccount;
    /**
     * Hypurr registry ID; zero is valid. No caller-supplied venue or symbol.
     *
     * @generated from protobuf field: int64 security_id = 2
     */
    securityId: number;
    /**
     * @generated from protobuf field: aconnect.Side side = 3
     */
    side: Side;
    /**
     * @generated from protobuf field: aconnect.OrderType order_type = 4
     */
    orderType: OrderType;
    /**
     * @generated from protobuf field: aconnect.TimeInForce time_in_force = 5
     */
    timeInForce: TimeInForce;
    /**
     * @generated from protobuf field: double quantity = 6
     */
    quantity: number;
    /**
     * @generated from protobuf field: optional double price = 7
     */
    price?: number;
    /**
     * @generated from protobuf field: string client_order_id = 8
     */
    clientOrderId: string;
    /**
     * @generated from protobuf field: bool reduce_only = 9
     */
    reduceOnly: boolean;
    /**
     * @generated from protobuf field: bool post_only = 10
     */
    postOnly: boolean;
}
/**
 * @generated from protobuf message aconnect.CancelOrderRequest
 */
export interface CancelOrderRequest {
    /**
     * @generated from protobuf field: aconnect.ExecutionAccount account = 1
     */
    account?: ExecutionAccount;
    /**
     * @generated from protobuf field: int64 security_id = 2
     */
    securityId: number;
    /**
     * @generated from protobuf oneof: identifier
     */
    identifier: {
        oneofKind: "orderId";
        /**
         * @generated from protobuf field: string order_id = 3
         */
        orderId: string;
    } | {
        oneofKind: "clientOrderId";
        /**
         * @generated from protobuf field: string client_order_id = 4
         */
        clientOrderId: string;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message aconnect.OrderResponse
 */
export interface OrderResponse {
    /**
     * @generated from protobuf field: int64 security_id = 1
     */
    securityId: number;
    /**
     * @generated from protobuf field: aconnect.Outcome outcome = 2
     */
    outcome: Outcome;
    /**
     * @generated from protobuf field: string order_id = 3
     */
    orderId: string;
    /**
     * @generated from protobuf field: string rejection_reason = 4
     */
    rejectionReason: string;
}
/**
 * @generated from protobuf enum aconnect.Side
 */
export enum Side {
    /**
     * @generated from protobuf enum value: SIDE_UNSPECIFIED = 0;
     */
    SIDE_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: BUY = 1;
     */
    BUY = 1,
    /**
     * @generated from protobuf enum value: SELL = 2;
     */
    SELL = 2
}
/**
 * @generated from protobuf enum aconnect.OrderType
 */
export enum OrderType {
    /**
     * @generated from protobuf enum value: ORDER_TYPE_UNSPECIFIED = 0;
     */
    ORDER_TYPE_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: LIMIT = 1;
     */
    LIMIT = 1,
    /**
     * @generated from protobuf enum value: MARKET = 2;
     */
    MARKET = 2
}
/**
 * @generated from protobuf enum aconnect.TimeInForce
 */
export enum TimeInForce {
    /**
     * @generated from protobuf enum value: TIME_IN_FORCE_UNSPECIFIED = 0;
     */
    TIME_IN_FORCE_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: GOOD_TILL_CANCEL = 1;
     */
    GOOD_TILL_CANCEL = 1,
    /**
     * @generated from protobuf enum value: IMMEDIATE_OR_CANCEL = 2;
     */
    IMMEDIATE_OR_CANCEL = 2,
    /**
     * @generated from protobuf enum value: FILL_OR_KILL = 3;
     */
    FILL_OR_KILL = 3,
    /**
     * @generated from protobuf enum value: POST_ONLY = 4;
     */
    POST_ONLY = 4
}
/**
 * @generated from protobuf enum aconnect.Outcome
 */
export enum Outcome {
    /**
     * @generated from protobuf enum value: OUTCOME_UNSPECIFIED = 0;
     */
    OUTCOME_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: ACCEPTED = 1;
     */
    ACCEPTED = 1,
    /**
     * @generated from protobuf enum value: REJECTED = 2;
     */
    REJECTED = 2,
    /**
     * Execution may have happened. Reconcile before submitting again.
     *
     * @generated from protobuf enum value: UNKNOWN = 3;
     */
    UNKNOWN = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class ExecutionAccount$Type extends MessageType<ExecutionAccount> {
    constructor() {
        super("aconnect.ExecutionAccount", [
            { no: 2, name: "exchange_account_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 2 /*LongType.NUMBER*/ }
        ]);
    }
    create(value?: PartialMessage<ExecutionAccount>): ExecutionAccount {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.exchangeAccountId = 0;
        if (value !== undefined)
            reflectionMergePartial<ExecutionAccount>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ExecutionAccount): ExecutionAccount {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 exchange_account_id */ 2:
                    message.exchangeAccountId = reader.int64().toNumber();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ExecutionAccount, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 exchange_account_id = 2; */
        if (message.exchangeAccountId !== 0)
            writer.tag(2, WireType.Varint).int64(message.exchangeAccountId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message aconnect.ExecutionAccount
 */
export const ExecutionAccount = new ExecutionAccount$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PlaceOrderRequest$Type extends MessageType<PlaceOrderRequest> {
    constructor() {
        super("aconnect.PlaceOrderRequest", [
            { no: 1, name: "account", kind: "message", T: () => ExecutionAccount },
            { no: 2, name: "security_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 3, name: "side", kind: "enum", T: () => ["aconnect.Side", Side] },
            { no: 4, name: "order_type", kind: "enum", T: () => ["aconnect.OrderType", OrderType] },
            { no: 5, name: "time_in_force", kind: "enum", T: () => ["aconnect.TimeInForce", TimeInForce] },
            { no: 6, name: "quantity", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 7, name: "price", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 8, name: "client_order_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "reduce_only", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 10, name: "post_only", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<PlaceOrderRequest>): PlaceOrderRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.securityId = 0;
        message.side = 0;
        message.orderType = 0;
        message.timeInForce = 0;
        message.quantity = 0;
        message.clientOrderId = "";
        message.reduceOnly = false;
        message.postOnly = false;
        if (value !== undefined)
            reflectionMergePartial<PlaceOrderRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PlaceOrderRequest): PlaceOrderRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* aconnect.ExecutionAccount account */ 1:
                    message.account = ExecutionAccount.internalBinaryRead(reader, reader.uint32(), options, message.account);
                    break;
                case /* int64 security_id */ 2:
                    message.securityId = reader.int64().toNumber();
                    break;
                case /* aconnect.Side side */ 3:
                    message.side = reader.int32();
                    break;
                case /* aconnect.OrderType order_type */ 4:
                    message.orderType = reader.int32();
                    break;
                case /* aconnect.TimeInForce time_in_force */ 5:
                    message.timeInForce = reader.int32();
                    break;
                case /* double quantity */ 6:
                    message.quantity = reader.double();
                    break;
                case /* optional double price */ 7:
                    message.price = reader.double();
                    break;
                case /* string client_order_id */ 8:
                    message.clientOrderId = reader.string();
                    break;
                case /* bool reduce_only */ 9:
                    message.reduceOnly = reader.bool();
                    break;
                case /* bool post_only */ 10:
                    message.postOnly = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PlaceOrderRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* aconnect.ExecutionAccount account = 1; */
        if (message.account)
            ExecutionAccount.internalBinaryWrite(message.account, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int64 security_id = 2; */
        if (message.securityId !== 0)
            writer.tag(2, WireType.Varint).int64(message.securityId);
        /* aconnect.Side side = 3; */
        if (message.side !== 0)
            writer.tag(3, WireType.Varint).int32(message.side);
        /* aconnect.OrderType order_type = 4; */
        if (message.orderType !== 0)
            writer.tag(4, WireType.Varint).int32(message.orderType);
        /* aconnect.TimeInForce time_in_force = 5; */
        if (message.timeInForce !== 0)
            writer.tag(5, WireType.Varint).int32(message.timeInForce);
        /* double quantity = 6; */
        if (message.quantity !== 0)
            writer.tag(6, WireType.Bit64).double(message.quantity);
        /* optional double price = 7; */
        if (message.price !== undefined)
            writer.tag(7, WireType.Bit64).double(message.price);
        /* string client_order_id = 8; */
        if (message.clientOrderId !== "")
            writer.tag(8, WireType.LengthDelimited).string(message.clientOrderId);
        /* bool reduce_only = 9; */
        if (message.reduceOnly !== false)
            writer.tag(9, WireType.Varint).bool(message.reduceOnly);
        /* bool post_only = 10; */
        if (message.postOnly !== false)
            writer.tag(10, WireType.Varint).bool(message.postOnly);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message aconnect.PlaceOrderRequest
 */
export const PlaceOrderRequest = new PlaceOrderRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CancelOrderRequest$Type extends MessageType<CancelOrderRequest> {
    constructor() {
        super("aconnect.CancelOrderRequest", [
            { no: 1, name: "account", kind: "message", T: () => ExecutionAccount },
            { no: 2, name: "security_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 3, name: "order_id", kind: "scalar", oneof: "identifier", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "client_order_id", kind: "scalar", oneof: "identifier", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CancelOrderRequest>): CancelOrderRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.securityId = 0;
        message.identifier = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<CancelOrderRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CancelOrderRequest): CancelOrderRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* aconnect.ExecutionAccount account */ 1:
                    message.account = ExecutionAccount.internalBinaryRead(reader, reader.uint32(), options, message.account);
                    break;
                case /* int64 security_id */ 2:
                    message.securityId = reader.int64().toNumber();
                    break;
                case /* string order_id */ 3:
                    message.identifier = {
                        oneofKind: "orderId",
                        orderId: reader.string()
                    };
                    break;
                case /* string client_order_id */ 4:
                    message.identifier = {
                        oneofKind: "clientOrderId",
                        clientOrderId: reader.string()
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CancelOrderRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* aconnect.ExecutionAccount account = 1; */
        if (message.account)
            ExecutionAccount.internalBinaryWrite(message.account, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int64 security_id = 2; */
        if (message.securityId !== 0)
            writer.tag(2, WireType.Varint).int64(message.securityId);
        /* string order_id = 3; */
        if (message.identifier.oneofKind === "orderId")
            writer.tag(3, WireType.LengthDelimited).string(message.identifier.orderId);
        /* string client_order_id = 4; */
        if (message.identifier.oneofKind === "clientOrderId")
            writer.tag(4, WireType.LengthDelimited).string(message.identifier.clientOrderId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message aconnect.CancelOrderRequest
 */
export const CancelOrderRequest = new CancelOrderRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OrderResponse$Type extends MessageType<OrderResponse> {
    constructor() {
        super("aconnect.OrderResponse", [
            { no: 1, name: "security_id", kind: "scalar", T: 3 /*ScalarType.INT64*/, L: 2 /*LongType.NUMBER*/ },
            { no: 2, name: "outcome", kind: "enum", T: () => ["aconnect.Outcome", Outcome] },
            { no: 3, name: "order_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "rejection_reason", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<OrderResponse>): OrderResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.securityId = 0;
        message.outcome = 0;
        message.orderId = "";
        message.rejectionReason = "";
        if (value !== undefined)
            reflectionMergePartial<OrderResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: OrderResponse): OrderResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int64 security_id */ 1:
                    message.securityId = reader.int64().toNumber();
                    break;
                case /* aconnect.Outcome outcome */ 2:
                    message.outcome = reader.int32();
                    break;
                case /* string order_id */ 3:
                    message.orderId = reader.string();
                    break;
                case /* string rejection_reason */ 4:
                    message.rejectionReason = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: OrderResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int64 security_id = 1; */
        if (message.securityId !== 0)
            writer.tag(1, WireType.Varint).int64(message.securityId);
        /* aconnect.Outcome outcome = 2; */
        if (message.outcome !== 0)
            writer.tag(2, WireType.Varint).int32(message.outcome);
        /* string order_id = 3; */
        if (message.orderId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.orderId);
        /* string rejection_reason = 4; */
        if (message.rejectionReason !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.rejectionReason);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message aconnect.OrderResponse
 */
export const OrderResponse = new OrderResponse$Type();
/**
 * @generated ServiceType for protobuf service aconnect.AConnect
 */
export const AConnect = new ServiceType("aconnect.AConnect", [
    { name: "PlaceOrder", options: {}, I: PlaceOrderRequest, O: OrderResponse },
    { name: "CancelOrder", options: {}, I: CancelOrderRequest, O: OrderResponse }
]);
