syntax = "proto3";

package hypurr;
option go_package = "gitlab.com/hypurr/hypurr-grpc/go/hypurr";

import "hypurr/common.proto";

// HPump Launch Token messages
message HpumpV1LaunchToken {
  string address = 1;          // token address is unique
  string symbol = 2;
  string name = 3;
  string dev_address = 4;
  string pair_address = 5;
  int64 created_at = 6;        // block timestamp
  string launch_id = 7;        // the uint256 id from the event (using string for big integers)
  bool graduated = 8;
  int64 graduated_at = 9;      // Timestamp when graduated
  HpumpV1LaunchPair pair = 10; // Embedded pair information
  string description = 11;
  int64 dev_telegram_id = 12;
  // Dev telegram user
  TelegramUserPublic dev_telegram_user = 13;
}

// HPump Launch Pair messages
message HpumpV1LaunchPair {
  string address = 1;           // pair address is unique
  string token = 2;             // reference to the token
  string base_reserve = 3;      // Using string for big integers
  string quote_reserve = 4;     // Using string for big integers
  string x0 = 5;
  int64 last_sync_timestamp = 6;
  string graduated_to = 7;      // Address of the new pair after graduation
  repeated HpumpV1LaunchPairSwap swaps = 8;  // List of swaps
}

// HPump Launch Pair Swap messages
message HpumpV1LaunchPairSwap {
  string id = 1;               // tx hash + log index
  string pair = 2;             // launch pair address
  string sender = 3;
  string origin = 4;
  string to = 5;
  string net_base_amount = 6;
  string net_quote_amount = 7;        // Using string for big integers
  int32 block_number = 8;
  int64 timestamp = 9;
}