syntax = "proto3";
package hypurr;
option go_package = "gitlab.com/hypurr/hypurr-grpc/go/hypurr";

import "google/protobuf/wrappers.proto";

import "hypurr/token.proto";
import "hypurr/wallet.proto";
import "hypurr/launch.proto";
import "hypurr/pairs.proto";
import "hypurr/cabal.proto";
import "hypurr/evm.proto";

message WalletMovementsRequest {
  string wallet_address = 1;
}

message WalletMovementsResponse {
  repeated HyperliquidWalletMovement wallet_movements = 1;
}

service HyperCore {
  rpc WalletMovements(WalletMovementsRequest) returns (WalletMovementsResponse) {}
}

/*
message HyperliquidWalletMovement {
  google.protobuf.Int64Value telegram_id = 1;
  HyperliquidWallet wallet = 2;
  int64 wallet_id = 3;
  string hash = 4;
  string type = 5;
  int64 token_id = 6;
  HyperliquidToken token = 7;
  double amount = 8;
  double usdc_value = 9;
  string destination = 10;
  double fee = 11;
  google.protobuf.Int64Value timestamp = 12;
}
 */