syntax = "proto3";
package hypurr;
option go_package = "gitlab.com/hypurr/hypurr-grpc/go/hypurr";
import "google/protobuf/wrappers.proto";

enum TradeDirection {
  BUY = 0;
  SELL = 1;
}

enum TimeInForce {
  GTC = 0;
  ALO = 1;
  IOC = 2;
}

message LimitOrderTypeData {
  TimeInForce time_in_force = 1;
}

message TriggerOrderTypeData {
  double trigger_price = 1;
  bool is_market = 2;
  double tpsl = 3;
}

message OrderType {
  oneof type {
    LimitOrderTypeData limit = 1;
    TriggerOrderTypeData trigger = 2;
  }
}

message HyperliquidCoreOrder {
  int64 instrument_id = 1;
  TradeDirection direction = 2;
  double limit_price = 3;
  double size = 4;
  bool reduce_only = 5;
  OrderType order_type = 6;
  google.protobuf.StringValue client_order_id = 7;
}

message HyperliquidCoreCancel {
  int64 instrument_id = 1;
  google.protobuf.Int64Value order_id = 2;
  google.protobuf.StringValue client_order_id = 3;
}

message HyperliquidCoreOrderPlacedStatus {
  string state = 1;
  HyperliquidCoreOrderFilled filled = 2;
  HyperliquidCoreOrderResting resting = 3;
}

message HyperliquidCoreOrderCanceledStatus {
  string state = 1;
  string error = 2;
}

message HyperliquidCoreOrderResting {
  int64 order_id = 1;
  google.protobuf.StringValue client_order_id = 2;
}

message HyperliquidCoreOrderFilled {
  int64 order_id = 1;
  double total_size = 2;
  double average_price = 3;
}