// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: hypurr/common.proto

package hypurr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaType int32

const (
	MediaType_MEDIA_TYPE_PHOTO     MediaType = 0
	MediaType_MEDIA_TYPE_ANIMATION MediaType = 1
	MediaType_MEDIA_TYPE_VIDEO     MediaType = 2
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "MEDIA_TYPE_PHOTO",
		1: "MEDIA_TYPE_ANIMATION",
		2: "MEDIA_TYPE_VIDEO",
	}
	MediaType_value = map[string]int32{
		"MEDIA_TYPE_PHOTO":     0,
		"MEDIA_TYPE_ANIMATION": 1,
		"MEDIA_TYPE_VIDEO":     2,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_hypurr_common_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_hypurr_common_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_hypurr_common_proto_rawDescGZIP(), []int{0}
}

type TelegramUserPublic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Username        string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	PictureFileId   string `protobuf:"bytes,3,opt,name=picture_file_id,json=pictureFileId,proto3" json:"picture_file_id,omitempty"`
	ReputationScore int64  `protobuf:"varint,4,opt,name=reputation_score,json=reputationScore,proto3" json:"reputation_score,omitempty"`
}

func (x *TelegramUserPublic) Reset() {
	*x = TelegramUserPublic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hypurr_common_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TelegramUserPublic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelegramUserPublic) ProtoMessage() {}

func (x *TelegramUserPublic) ProtoReflect() protoreflect.Message {
	mi := &file_hypurr_common_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelegramUserPublic.ProtoReflect.Descriptor instead.
func (*TelegramUserPublic) Descriptor() ([]byte, []int) {
	return file_hypurr_common_proto_rawDescGZIP(), []int{0}
}

func (x *TelegramUserPublic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TelegramUserPublic) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TelegramUserPublic) GetPictureFileId() string {
	if x != nil {
		return x.PictureFileId
	}
	return ""
}

func (x *TelegramUserPublic) GetReputationScore() int64 {
	if x != nil {
		return x.ReputationScore
	}
	return 0
}

type PriceCandle struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Time        int64   `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Open        float32 `protobuf:"fixed32,2,opt,name=open,proto3" json:"open,omitempty"`
	High        float32 `protobuf:"fixed32,3,opt,name=high,proto3" json:"high,omitempty"`
	Low         float32 `protobuf:"fixed32,4,opt,name=low,proto3" json:"low,omitempty"`
	Close       float32 `protobuf:"fixed32,5,opt,name=close,proto3" json:"close,omitempty"`
	VolumeBase  float32 `protobuf:"fixed32,6,opt,name=volume_base,json=volumeBase,proto3" json:"volume_base,omitempty"`
	VolumeQuote float32 `protobuf:"fixed32,7,opt,name=volume_quote,json=volumeQuote,proto3" json:"volume_quote,omitempty"`
}

func (x *PriceCandle) Reset() {
	*x = PriceCandle{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hypurr_common_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PriceCandle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceCandle) ProtoMessage() {}

func (x *PriceCandle) ProtoReflect() protoreflect.Message {
	mi := &file_hypurr_common_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceCandle.ProtoReflect.Descriptor instead.
func (*PriceCandle) Descriptor() ([]byte, []int) {
	return file_hypurr_common_proto_rawDescGZIP(), []int{1}
}

func (x *PriceCandle) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *PriceCandle) GetOpen() float32 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *PriceCandle) GetHigh() float32 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *PriceCandle) GetLow() float32 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *PriceCandle) GetClose() float32 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *PriceCandle) GetVolumeBase() float32 {
	if x != nil {
		return x.VolumeBase
	}
	return 0
}

func (x *PriceCandle) GetVolumeQuote() float32 {
	if x != nil {
		return x.VolumeQuote
	}
	return 0
}

type WalletPosition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string  `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Balance float32 `protobuf:"fixed32,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Cost    float32 `protobuf:"fixed32,3,opt,name=cost,proto3" json:"cost,omitempty"`
}

func (x *WalletPosition) Reset() {
	*x = WalletPosition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hypurr_common_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WalletPosition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WalletPosition) ProtoMessage() {}

func (x *WalletPosition) ProtoReflect() protoreflect.Message {
	mi := &file_hypurr_common_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WalletPosition.ProtoReflect.Descriptor instead.
func (*WalletPosition) Descriptor() ([]byte, []int) {
	return file_hypurr_common_proto_rawDescGZIP(), []int{2}
}

func (x *WalletPosition) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *WalletPosition) GetBalance() float32 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *WalletPosition) GetCost() float32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

var File_hypurr_common_proto protoreflect.FileDescriptor

var file_hypurr_common_proto_rawDesc = []byte{
	0x0a, 0x13, 0x68, 0x79, 0x70, 0x75, 0x72, 0x72, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x68, 0x79, 0x70, 0x75, 0x72, 0x72, 0x22, 0x93, 0x01,
	0x0a, 0x12, 0x54, 0x65, 0x6c, 0x65, 0x67, 0x72, 0x61, 0x6d, 0x55, 0x73, 0x65, 0x72, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x26, 0x0a, 0x0f, 0x70, 0x69, 0x63, 0x74, 0x75, 0x72, 0x65, 0x5f, 0x66, 0x69, 0x6c, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x69, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x46, 0x69, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x65, 0x70, 0x75,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0f, 0x72, 0x65, 0x70, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x63,
	0x6f, 0x72, 0x65, 0x22, 0xb5, 0x01, 0x0a, 0x0b, 0x50, 0x72, 0x69, 0x63, 0x65, 0x43, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x04, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x69, 0x67, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x12,
	0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x6f,
	0x77, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x05, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x76, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x5f, 0x62, 0x61, 0x73, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0a, 0x76, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x42, 0x61, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x76, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x5f, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b,
	0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x22, 0x58, 0x0a, 0x0e, 0x57,
	0x61, 0x6c, 0x6c, 0x65, 0x74, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x04, 0x63, 0x6f, 0x73, 0x74, 0x2a, 0x51, 0x0a, 0x09, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x45, 0x44, 0x49, 0x41, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x50, 0x48, 0x4f, 0x54, 0x4f, 0x10, 0x00, 0x12, 0x18, 0x0a, 0x14, 0x4d, 0x45, 0x44, 0x49,
	0x41, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x4e, 0x49, 0x4d, 0x41, 0x54, 0x49, 0x4f, 0x4e,
	0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x45, 0x44, 0x49, 0x41, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x5f, 0x56, 0x49, 0x44, 0x45, 0x4f, 0x10, 0x02, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x6c,
	0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x68, 0x79, 0x70, 0x75, 0x72, 0x72, 0x2f, 0x68, 0x79,
	0x70, 0x75, 0x72, 0x72, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x67, 0x6f, 0x2f, 0x68, 0x79, 0x70,
	0x75, 0x72, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hypurr_common_proto_rawDescOnce sync.Once
	file_hypurr_common_proto_rawDescData = file_hypurr_common_proto_rawDesc
)

func file_hypurr_common_proto_rawDescGZIP() []byte {
	file_hypurr_common_proto_rawDescOnce.Do(func() {
		file_hypurr_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_hypurr_common_proto_rawDescData)
	})
	return file_hypurr_common_proto_rawDescData
}

var file_hypurr_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_hypurr_common_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_hypurr_common_proto_goTypes = []any{
	(MediaType)(0),             // 0: hypurr.MediaType
	(*TelegramUserPublic)(nil), // 1: hypurr.TelegramUserPublic
	(*PriceCandle)(nil),        // 2: hypurr.PriceCandle
	(*WalletPosition)(nil),     // 3: hypurr.WalletPosition
}
var file_hypurr_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_hypurr_common_proto_init() }
func file_hypurr_common_proto_init() {
	if File_hypurr_common_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hypurr_common_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*TelegramUserPublic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hypurr_common_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PriceCandle); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hypurr_common_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*WalletPosition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hypurr_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hypurr_common_proto_goTypes,
		DependencyIndexes: file_hypurr_common_proto_depIdxs,
		EnumInfos:         file_hypurr_common_proto_enumTypes,
		MessageInfos:      file_hypurr_common_proto_msgTypes,
	}.Build()
	File_hypurr_common_proto = out.File
	file_hypurr_common_proto_rawDesc = nil
	file_hypurr_common_proto_goTypes = nil
	file_hypurr_common_proto_depIdxs = nil
}
