// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.21.12
// source: hypurr/evm_service.proto

package hypurr

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	EVM_ERC20Token_FullMethodName                  = "/hypurr.EVM/ERC20Token"
	EVM_ERC20Tokens_FullMethodName                 = "/hypurr.EVM/ERC20Tokens"
	EVM_ERC20AccountBalances_FullMethodName        = "/hypurr.EVM/ERC20AccountBalances"
	EVM_UniV2Pair_FullMethodName                   = "/hypurr.EVM/UniV2Pair"
	EVM_UniPairs_FullMethodName                    = "/hypurr.EVM/UniPairs"
	EVM_UniV2Swap_FullMethodName                   = "/hypurr.EVM/UniV2Swap"
	EVM_UniV2Swaps_FullMethodName                  = "/hypurr.EVM/UniV2Swaps"
	EVM_UniV3Swap_FullMethodName                   = "/hypurr.EVM/UniV3Swap"
	EVM_UniV3Swaps_FullMethodName                  = "/hypurr.EVM/UniV3Swaps"
	EVM_ERC20TransferEvents_FullMethodName         = "/hypurr.EVM/ERC20TransferEvents"
	EVM_ERC20ApprovalEvents_FullMethodName         = "/hypurr.EVM/ERC20ApprovalEvents"
	EVM_UniCandles_FullMethodName                  = "/hypurr.EVM/UniCandles"
	EVM_UniV2SwapStream_FullMethodName             = "/hypurr.EVM/UniV2SwapStream"
	EVM_UniV3SwapStream_FullMethodName             = "/hypurr.EVM/UniV3SwapStream"
	EVM_HpumpV1LaunchToken_FullMethodName          = "/hypurr.EVM/HpumpV1LaunchToken"
	EVM_HpumpV1LaunchTokens_FullMethodName         = "/hypurr.EVM/HpumpV1LaunchTokens"
	EVM_HpumpV1LaunchPair_FullMethodName           = "/hypurr.EVM/HpumpV1LaunchPair"
	EVM_HpumpV1LaunchPairs_FullMethodName          = "/hypurr.EVM/HpumpV1LaunchPairs"
	EVM_HpumpV1LaunchPairSwap_FullMethodName       = "/hypurr.EVM/HpumpV1LaunchPairSwap"
	EVM_HpumpV1LaunchPairSwaps_FullMethodName      = "/hypurr.EVM/HpumpV1LaunchPairSwaps"
	EVM_HpumpV1LaunchPairSwapStream_FullMethodName = "/hypurr.EVM/HpumpV1LaunchPairSwapStream"
	EVM_HpumpV1_FullMethodName                     = "/hypurr.EVM/HpumpV1"
)

// EVMClient is the client API for EVM service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EVMClient interface {
	// Token related endpoints
	ERC20Token(ctx context.Context, in *ERC20TokenRequest, opts ...grpc.CallOption) (*ERC20TokenResponse, error)
	ERC20Tokens(ctx context.Context, in *ERC20TokensRequest, opts ...grpc.CallOption) (*ERC20TokensResponse, error)
	ERC20AccountBalances(ctx context.Context, in *ERC20AccountBalancesRequest, opts ...grpc.CallOption) (*ERC20AccountBalancesResponse, error)
	// Pair related endpoints
	UniV2Pair(ctx context.Context, in *UniV2PairRequest, opts ...grpc.CallOption) (*UniV2PairResponse, error)
	UniPairs(ctx context.Context, in *UniPairsRequest, opts ...grpc.CallOption) (*UniPairsResponse, error)
	// Swap related endpoints
	UniV2Swap(ctx context.Context, in *UniV2SwapRequest, opts ...grpc.CallOption) (*UniV2SwapResponse, error)
	UniV2Swaps(ctx context.Context, in *UniV2SwapsRequest, opts ...grpc.CallOption) (*UniV2SwapsResponse, error)
	UniV3Swap(ctx context.Context, in *UniV3SwapRequest, opts ...grpc.CallOption) (*UniV3SwapResponse, error)
	UniV3Swaps(ctx context.Context, in *UniV3SwapsRequest, opts ...grpc.CallOption) (*UniV3SwapsResponse, error)
	// Event related endpoints
	ERC20TransferEvents(ctx context.Context, in *ERC20TransferEventsRequest, opts ...grpc.CallOption) (*ERC20TransferEventsResponse, error)
	ERC20ApprovalEvents(ctx context.Context, in *ERC20ApprovalEventsRequest, opts ...grpc.CallOption) (*ERC20ApprovalEventsResponse, error)
	// Price candle related endpoints
	UniCandles(ctx context.Context, in *UniCandlesRequest, opts ...grpc.CallOption) (*UniCandlesResponse, error)
	// Streaming endpoints
	UniV2SwapStream(ctx context.Context, in *UniV2SwapStreamRequest, opts ...grpc.CallOption) (EVM_UniV2SwapStreamClient, error)
	UniV3SwapStream(ctx context.Context, in *UniV3SwapStreamRequest, opts ...grpc.CallOption) (EVM_UniV3SwapStreamClient, error)
	// HPump V1 related endpoints
	HpumpV1LaunchToken(ctx context.Context, in *HpumpV1LaunchTokenRequest, opts ...grpc.CallOption) (*HpumpV1LaunchTokenResponse, error)
	HpumpV1LaunchTokens(ctx context.Context, in *HpumpV1LaunchTokensRequest, opts ...grpc.CallOption) (*HpumpV1LaunchTokensResponse, error)
	HpumpV1LaunchPair(ctx context.Context, in *HpumpV1LaunchPairRequest, opts ...grpc.CallOption) (*HpumpV1LaunchPairResponse, error)
	HpumpV1LaunchPairs(ctx context.Context, in *HpumpV1LaunchPairsRequest, opts ...grpc.CallOption) (*HpumpV1LaunchPairsResponse, error)
	HpumpV1LaunchPairSwap(ctx context.Context, in *HpumpV1LaunchPairSwapRequest, opts ...grpc.CallOption) (*HpumpV1LaunchPairSwapResponse, error)
	HpumpV1LaunchPairSwaps(ctx context.Context, in *HpumpV1LaunchPairSwapsRequest, opts ...grpc.CallOption) (*HpumpV1LaunchPairSwapsResponse, error)
	// HPump V1 streaming endpoint
	HpumpV1LaunchPairSwapStream(ctx context.Context, in *HpumpV1LaunchPairSwapStreamRequest, opts ...grpc.CallOption) (EVM_HpumpV1LaunchPairSwapStreamClient, error)
	// Price candle related endpoints
	// Todo group into same type
	HpumpV1(ctx context.Context, in *HpumpV1CandlesRequest, opts ...grpc.CallOption) (*HpumpV1CandlesResponse, error)
}

type eVMClient struct {
	cc grpc.ClientConnInterface
}

func NewEVMClient(cc grpc.ClientConnInterface) EVMClient {
	return &eVMClient{cc}
}

func (c *eVMClient) ERC20Token(ctx context.Context, in *ERC20TokenRequest, opts ...grpc.CallOption) (*ERC20TokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ERC20TokenResponse)
	err := c.cc.Invoke(ctx, EVM_ERC20Token_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eVMClient) ERC20Tokens(ctx context.Context, in *ERC20TokensRequest, opts ...grpc.CallOption) (*ERC20TokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ERC20TokensResponse)
	err := c.cc.Invoke(ctx, EVM_ERC20Tokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eVMClient) ERC20AccountBalances(ctx context.Context, in *ERC20AccountBalancesRequest, opts ...grpc.CallOption) (*ERC20AccountBalancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ERC20AccountBalancesResponse)
	err := c.cc.Invoke(ctx, EVM_ERC20AccountBalances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eVMClient) UniV2Pair(ctx context.Context, in *UniV2PairRequest, opts ...grpc.CallOption) (*UniV2PairResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UniV2PairResponse)
	err := c.cc.Invoke(ctx, EVM_UniV2Pair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eVMClient) UniPairs(ctx context.Context, in *UniPairsRequest, opts ...grpc.CallOption) (*UniPairsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UniPairsResponse)
	err := c.cc.Invoke(ctx, EVM_UniPairs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eVMClient) UniV2Swap(ctx context.Context, in *UniV2SwapRequest, opts ...grpc.CallOption) (*UniV2SwapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UniV2SwapResponse)
	err := c.cc.Invoke(ctx, EVM_UniV2Swap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eVMClient) UniV2Swaps(ctx context.Context, in *UniV2SwapsRequest, opts ...grpc.CallOption) (*UniV2SwapsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UniV2SwapsResponse)
	err := c.cc.Invoke(ctx, EVM_UniV2Swaps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eVMClient) UniV3Swap(ctx context.Context, in *UniV3SwapRequest, opts ...grpc.CallOption) (*UniV3SwapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UniV3SwapResponse)
	err := c.cc.Invoke(ctx, EVM_UniV3Swap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eVMClient) UniV3Swaps(ctx context.Context, in *UniV3SwapsRequest, opts ...grpc.CallOption) (*UniV3SwapsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UniV3SwapsResponse)
	err := c.cc.Invoke(ctx, EVM_UniV3Swaps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eVMClient) ERC20TransferEvents(ctx context.Context, in *ERC20TransferEventsRequest, opts ...grpc.CallOption) (*ERC20TransferEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ERC20TransferEventsResponse)
	err := c.cc.Invoke(ctx, EVM_ERC20TransferEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eVMClient) ERC20ApprovalEvents(ctx context.Context, in *ERC20ApprovalEventsRequest, opts ...grpc.CallOption) (*ERC20ApprovalEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ERC20ApprovalEventsResponse)
	err := c.cc.Invoke(ctx, EVM_ERC20ApprovalEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eVMClient) UniCandles(ctx context.Context, in *UniCandlesRequest, opts ...grpc.CallOption) (*UniCandlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UniCandlesResponse)
	err := c.cc.Invoke(ctx, EVM_UniCandles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eVMClient) UniV2SwapStream(ctx context.Context, in *UniV2SwapStreamRequest, opts ...grpc.CallOption) (EVM_UniV2SwapStreamClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EVM_ServiceDesc.Streams[0], EVM_UniV2SwapStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &eVMUniV2SwapStreamClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EVM_UniV2SwapStreamClient interface {
	Recv() (*UniV2SwapStreamResponse, error)
	grpc.ClientStream
}

type eVMUniV2SwapStreamClient struct {
	grpc.ClientStream
}

func (x *eVMUniV2SwapStreamClient) Recv() (*UniV2SwapStreamResponse, error) {
	m := new(UniV2SwapStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *eVMClient) UniV3SwapStream(ctx context.Context, in *UniV3SwapStreamRequest, opts ...grpc.CallOption) (EVM_UniV3SwapStreamClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EVM_ServiceDesc.Streams[1], EVM_UniV3SwapStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &eVMUniV3SwapStreamClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EVM_UniV3SwapStreamClient interface {
	Recv() (*UniV3SwapStreamResponse, error)
	grpc.ClientStream
}

type eVMUniV3SwapStreamClient struct {
	grpc.ClientStream
}

func (x *eVMUniV3SwapStreamClient) Recv() (*UniV3SwapStreamResponse, error) {
	m := new(UniV3SwapStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *eVMClient) HpumpV1LaunchToken(ctx context.Context, in *HpumpV1LaunchTokenRequest, opts ...grpc.CallOption) (*HpumpV1LaunchTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HpumpV1LaunchTokenResponse)
	err := c.cc.Invoke(ctx, EVM_HpumpV1LaunchToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eVMClient) HpumpV1LaunchTokens(ctx context.Context, in *HpumpV1LaunchTokensRequest, opts ...grpc.CallOption) (*HpumpV1LaunchTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HpumpV1LaunchTokensResponse)
	err := c.cc.Invoke(ctx, EVM_HpumpV1LaunchTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eVMClient) HpumpV1LaunchPair(ctx context.Context, in *HpumpV1LaunchPairRequest, opts ...grpc.CallOption) (*HpumpV1LaunchPairResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HpumpV1LaunchPairResponse)
	err := c.cc.Invoke(ctx, EVM_HpumpV1LaunchPair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eVMClient) HpumpV1LaunchPairs(ctx context.Context, in *HpumpV1LaunchPairsRequest, opts ...grpc.CallOption) (*HpumpV1LaunchPairsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HpumpV1LaunchPairsResponse)
	err := c.cc.Invoke(ctx, EVM_HpumpV1LaunchPairs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eVMClient) HpumpV1LaunchPairSwap(ctx context.Context, in *HpumpV1LaunchPairSwapRequest, opts ...grpc.CallOption) (*HpumpV1LaunchPairSwapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HpumpV1LaunchPairSwapResponse)
	err := c.cc.Invoke(ctx, EVM_HpumpV1LaunchPairSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eVMClient) HpumpV1LaunchPairSwaps(ctx context.Context, in *HpumpV1LaunchPairSwapsRequest, opts ...grpc.CallOption) (*HpumpV1LaunchPairSwapsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HpumpV1LaunchPairSwapsResponse)
	err := c.cc.Invoke(ctx, EVM_HpumpV1LaunchPairSwaps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *eVMClient) HpumpV1LaunchPairSwapStream(ctx context.Context, in *HpumpV1LaunchPairSwapStreamRequest, opts ...grpc.CallOption) (EVM_HpumpV1LaunchPairSwapStreamClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EVM_ServiceDesc.Streams[2], EVM_HpumpV1LaunchPairSwapStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &eVMHpumpV1LaunchPairSwapStreamClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type EVM_HpumpV1LaunchPairSwapStreamClient interface {
	Recv() (*HpumpV1LaunchPairSwapStreamResponse, error)
	grpc.ClientStream
}

type eVMHpumpV1LaunchPairSwapStreamClient struct {
	grpc.ClientStream
}

func (x *eVMHpumpV1LaunchPairSwapStreamClient) Recv() (*HpumpV1LaunchPairSwapStreamResponse, error) {
	m := new(HpumpV1LaunchPairSwapStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *eVMClient) HpumpV1(ctx context.Context, in *HpumpV1CandlesRequest, opts ...grpc.CallOption) (*HpumpV1CandlesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HpumpV1CandlesResponse)
	err := c.cc.Invoke(ctx, EVM_HpumpV1_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EVMServer is the server API for EVM service.
// All implementations must embed UnimplementedEVMServer
// for forward compatibility
type EVMServer interface {
	// Token related endpoints
	ERC20Token(context.Context, *ERC20TokenRequest) (*ERC20TokenResponse, error)
	ERC20Tokens(context.Context, *ERC20TokensRequest) (*ERC20TokensResponse, error)
	ERC20AccountBalances(context.Context, *ERC20AccountBalancesRequest) (*ERC20AccountBalancesResponse, error)
	// Pair related endpoints
	UniV2Pair(context.Context, *UniV2PairRequest) (*UniV2PairResponse, error)
	UniPairs(context.Context, *UniPairsRequest) (*UniPairsResponse, error)
	// Swap related endpoints
	UniV2Swap(context.Context, *UniV2SwapRequest) (*UniV2SwapResponse, error)
	UniV2Swaps(context.Context, *UniV2SwapsRequest) (*UniV2SwapsResponse, error)
	UniV3Swap(context.Context, *UniV3SwapRequest) (*UniV3SwapResponse, error)
	UniV3Swaps(context.Context, *UniV3SwapsRequest) (*UniV3SwapsResponse, error)
	// Event related endpoints
	ERC20TransferEvents(context.Context, *ERC20TransferEventsRequest) (*ERC20TransferEventsResponse, error)
	ERC20ApprovalEvents(context.Context, *ERC20ApprovalEventsRequest) (*ERC20ApprovalEventsResponse, error)
	// Price candle related endpoints
	UniCandles(context.Context, *UniCandlesRequest) (*UniCandlesResponse, error)
	// Streaming endpoints
	UniV2SwapStream(*UniV2SwapStreamRequest, EVM_UniV2SwapStreamServer) error
	UniV3SwapStream(*UniV3SwapStreamRequest, EVM_UniV3SwapStreamServer) error
	// HPump V1 related endpoints
	HpumpV1LaunchToken(context.Context, *HpumpV1LaunchTokenRequest) (*HpumpV1LaunchTokenResponse, error)
	HpumpV1LaunchTokens(context.Context, *HpumpV1LaunchTokensRequest) (*HpumpV1LaunchTokensResponse, error)
	HpumpV1LaunchPair(context.Context, *HpumpV1LaunchPairRequest) (*HpumpV1LaunchPairResponse, error)
	HpumpV1LaunchPairs(context.Context, *HpumpV1LaunchPairsRequest) (*HpumpV1LaunchPairsResponse, error)
	HpumpV1LaunchPairSwap(context.Context, *HpumpV1LaunchPairSwapRequest) (*HpumpV1LaunchPairSwapResponse, error)
	HpumpV1LaunchPairSwaps(context.Context, *HpumpV1LaunchPairSwapsRequest) (*HpumpV1LaunchPairSwapsResponse, error)
	// HPump V1 streaming endpoint
	HpumpV1LaunchPairSwapStream(*HpumpV1LaunchPairSwapStreamRequest, EVM_HpumpV1LaunchPairSwapStreamServer) error
	// Price candle related endpoints
	// Todo group into same type
	HpumpV1(context.Context, *HpumpV1CandlesRequest) (*HpumpV1CandlesResponse, error)
	mustEmbedUnimplementedEVMServer()
}

// UnimplementedEVMServer must be embedded to have forward compatible implementations.
type UnimplementedEVMServer struct {
}

func (UnimplementedEVMServer) ERC20Token(context.Context, *ERC20TokenRequest) (*ERC20TokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ERC20Token not implemented")
}
func (UnimplementedEVMServer) ERC20Tokens(context.Context, *ERC20TokensRequest) (*ERC20TokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ERC20Tokens not implemented")
}
func (UnimplementedEVMServer) ERC20AccountBalances(context.Context, *ERC20AccountBalancesRequest) (*ERC20AccountBalancesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ERC20AccountBalances not implemented")
}
func (UnimplementedEVMServer) UniV2Pair(context.Context, *UniV2PairRequest) (*UniV2PairResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UniV2Pair not implemented")
}
func (UnimplementedEVMServer) UniPairs(context.Context, *UniPairsRequest) (*UniPairsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UniPairs not implemented")
}
func (UnimplementedEVMServer) UniV2Swap(context.Context, *UniV2SwapRequest) (*UniV2SwapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UniV2Swap not implemented")
}
func (UnimplementedEVMServer) UniV2Swaps(context.Context, *UniV2SwapsRequest) (*UniV2SwapsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UniV2Swaps not implemented")
}
func (UnimplementedEVMServer) UniV3Swap(context.Context, *UniV3SwapRequest) (*UniV3SwapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UniV3Swap not implemented")
}
func (UnimplementedEVMServer) UniV3Swaps(context.Context, *UniV3SwapsRequest) (*UniV3SwapsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UniV3Swaps not implemented")
}
func (UnimplementedEVMServer) ERC20TransferEvents(context.Context, *ERC20TransferEventsRequest) (*ERC20TransferEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ERC20TransferEvents not implemented")
}
func (UnimplementedEVMServer) ERC20ApprovalEvents(context.Context, *ERC20ApprovalEventsRequest) (*ERC20ApprovalEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ERC20ApprovalEvents not implemented")
}
func (UnimplementedEVMServer) UniCandles(context.Context, *UniCandlesRequest) (*UniCandlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UniCandles not implemented")
}
func (UnimplementedEVMServer) UniV2SwapStream(*UniV2SwapStreamRequest, EVM_UniV2SwapStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method UniV2SwapStream not implemented")
}
func (UnimplementedEVMServer) UniV3SwapStream(*UniV3SwapStreamRequest, EVM_UniV3SwapStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method UniV3SwapStream not implemented")
}
func (UnimplementedEVMServer) HpumpV1LaunchToken(context.Context, *HpumpV1LaunchTokenRequest) (*HpumpV1LaunchTokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HpumpV1LaunchToken not implemented")
}
func (UnimplementedEVMServer) HpumpV1LaunchTokens(context.Context, *HpumpV1LaunchTokensRequest) (*HpumpV1LaunchTokensResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HpumpV1LaunchTokens not implemented")
}
func (UnimplementedEVMServer) HpumpV1LaunchPair(context.Context, *HpumpV1LaunchPairRequest) (*HpumpV1LaunchPairResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HpumpV1LaunchPair not implemented")
}
func (UnimplementedEVMServer) HpumpV1LaunchPairs(context.Context, *HpumpV1LaunchPairsRequest) (*HpumpV1LaunchPairsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HpumpV1LaunchPairs not implemented")
}
func (UnimplementedEVMServer) HpumpV1LaunchPairSwap(context.Context, *HpumpV1LaunchPairSwapRequest) (*HpumpV1LaunchPairSwapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HpumpV1LaunchPairSwap not implemented")
}
func (UnimplementedEVMServer) HpumpV1LaunchPairSwaps(context.Context, *HpumpV1LaunchPairSwapsRequest) (*HpumpV1LaunchPairSwapsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HpumpV1LaunchPairSwaps not implemented")
}
func (UnimplementedEVMServer) HpumpV1LaunchPairSwapStream(*HpumpV1LaunchPairSwapStreamRequest, EVM_HpumpV1LaunchPairSwapStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method HpumpV1LaunchPairSwapStream not implemented")
}
func (UnimplementedEVMServer) HpumpV1(context.Context, *HpumpV1CandlesRequest) (*HpumpV1CandlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HpumpV1 not implemented")
}
func (UnimplementedEVMServer) mustEmbedUnimplementedEVMServer() {}

// UnsafeEVMServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EVMServer will
// result in compilation errors.
type UnsafeEVMServer interface {
	mustEmbedUnimplementedEVMServer()
}

func RegisterEVMServer(s grpc.ServiceRegistrar, srv EVMServer) {
	s.RegisterService(&EVM_ServiceDesc, srv)
}

func _EVM_ERC20Token_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ERC20TokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EVMServer).ERC20Token(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EVM_ERC20Token_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EVMServer).ERC20Token(ctx, req.(*ERC20TokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EVM_ERC20Tokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ERC20TokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EVMServer).ERC20Tokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EVM_ERC20Tokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EVMServer).ERC20Tokens(ctx, req.(*ERC20TokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EVM_ERC20AccountBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ERC20AccountBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EVMServer).ERC20AccountBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EVM_ERC20AccountBalances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EVMServer).ERC20AccountBalances(ctx, req.(*ERC20AccountBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EVM_UniV2Pair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UniV2PairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EVMServer).UniV2Pair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EVM_UniV2Pair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EVMServer).UniV2Pair(ctx, req.(*UniV2PairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EVM_UniPairs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UniPairsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EVMServer).UniPairs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EVM_UniPairs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EVMServer).UniPairs(ctx, req.(*UniPairsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EVM_UniV2Swap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UniV2SwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EVMServer).UniV2Swap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EVM_UniV2Swap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EVMServer).UniV2Swap(ctx, req.(*UniV2SwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EVM_UniV2Swaps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UniV2SwapsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EVMServer).UniV2Swaps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EVM_UniV2Swaps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EVMServer).UniV2Swaps(ctx, req.(*UniV2SwapsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EVM_UniV3Swap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UniV3SwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EVMServer).UniV3Swap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EVM_UniV3Swap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EVMServer).UniV3Swap(ctx, req.(*UniV3SwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EVM_UniV3Swaps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UniV3SwapsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EVMServer).UniV3Swaps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EVM_UniV3Swaps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EVMServer).UniV3Swaps(ctx, req.(*UniV3SwapsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EVM_ERC20TransferEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ERC20TransferEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EVMServer).ERC20TransferEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EVM_ERC20TransferEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EVMServer).ERC20TransferEvents(ctx, req.(*ERC20TransferEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EVM_ERC20ApprovalEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ERC20ApprovalEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EVMServer).ERC20ApprovalEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EVM_ERC20ApprovalEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EVMServer).ERC20ApprovalEvents(ctx, req.(*ERC20ApprovalEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EVM_UniCandles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UniCandlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EVMServer).UniCandles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EVM_UniCandles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EVMServer).UniCandles(ctx, req.(*UniCandlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EVM_UniV2SwapStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UniV2SwapStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EVMServer).UniV2SwapStream(m, &eVMUniV2SwapStreamServer{ServerStream: stream})
}

type EVM_UniV2SwapStreamServer interface {
	Send(*UniV2SwapStreamResponse) error
	grpc.ServerStream
}

type eVMUniV2SwapStreamServer struct {
	grpc.ServerStream
}

func (x *eVMUniV2SwapStreamServer) Send(m *UniV2SwapStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _EVM_UniV3SwapStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UniV3SwapStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EVMServer).UniV3SwapStream(m, &eVMUniV3SwapStreamServer{ServerStream: stream})
}

type EVM_UniV3SwapStreamServer interface {
	Send(*UniV3SwapStreamResponse) error
	grpc.ServerStream
}

type eVMUniV3SwapStreamServer struct {
	grpc.ServerStream
}

func (x *eVMUniV3SwapStreamServer) Send(m *UniV3SwapStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _EVM_HpumpV1LaunchToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HpumpV1LaunchTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EVMServer).HpumpV1LaunchToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EVM_HpumpV1LaunchToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EVMServer).HpumpV1LaunchToken(ctx, req.(*HpumpV1LaunchTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EVM_HpumpV1LaunchTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HpumpV1LaunchTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EVMServer).HpumpV1LaunchTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EVM_HpumpV1LaunchTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EVMServer).HpumpV1LaunchTokens(ctx, req.(*HpumpV1LaunchTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EVM_HpumpV1LaunchPair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HpumpV1LaunchPairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EVMServer).HpumpV1LaunchPair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EVM_HpumpV1LaunchPair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EVMServer).HpumpV1LaunchPair(ctx, req.(*HpumpV1LaunchPairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EVM_HpumpV1LaunchPairs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HpumpV1LaunchPairsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EVMServer).HpumpV1LaunchPairs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EVM_HpumpV1LaunchPairs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EVMServer).HpumpV1LaunchPairs(ctx, req.(*HpumpV1LaunchPairsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EVM_HpumpV1LaunchPairSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HpumpV1LaunchPairSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EVMServer).HpumpV1LaunchPairSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EVM_HpumpV1LaunchPairSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EVMServer).HpumpV1LaunchPairSwap(ctx, req.(*HpumpV1LaunchPairSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EVM_HpumpV1LaunchPairSwaps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HpumpV1LaunchPairSwapsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EVMServer).HpumpV1LaunchPairSwaps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EVM_HpumpV1LaunchPairSwaps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EVMServer).HpumpV1LaunchPairSwaps(ctx, req.(*HpumpV1LaunchPairSwapsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EVM_HpumpV1LaunchPairSwapStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HpumpV1LaunchPairSwapStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EVMServer).HpumpV1LaunchPairSwapStream(m, &eVMHpumpV1LaunchPairSwapStreamServer{ServerStream: stream})
}

type EVM_HpumpV1LaunchPairSwapStreamServer interface {
	Send(*HpumpV1LaunchPairSwapStreamResponse) error
	grpc.ServerStream
}

type eVMHpumpV1LaunchPairSwapStreamServer struct {
	grpc.ServerStream
}

func (x *eVMHpumpV1LaunchPairSwapStreamServer) Send(m *HpumpV1LaunchPairSwapStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _EVM_HpumpV1_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HpumpV1CandlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EVMServer).HpumpV1(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EVM_HpumpV1_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EVMServer).HpumpV1(ctx, req.(*HpumpV1CandlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EVM_ServiceDesc is the grpc.ServiceDesc for EVM service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EVM_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hypurr.EVM",
	HandlerType: (*EVMServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ERC20Token",
			Handler:    _EVM_ERC20Token_Handler,
		},
		{
			MethodName: "ERC20Tokens",
			Handler:    _EVM_ERC20Tokens_Handler,
		},
		{
			MethodName: "ERC20AccountBalances",
			Handler:    _EVM_ERC20AccountBalances_Handler,
		},
		{
			MethodName: "UniV2Pair",
			Handler:    _EVM_UniV2Pair_Handler,
		},
		{
			MethodName: "UniPairs",
			Handler:    _EVM_UniPairs_Handler,
		},
		{
			MethodName: "UniV2Swap",
			Handler:    _EVM_UniV2Swap_Handler,
		},
		{
			MethodName: "UniV2Swaps",
			Handler:    _EVM_UniV2Swaps_Handler,
		},
		{
			MethodName: "UniV3Swap",
			Handler:    _EVM_UniV3Swap_Handler,
		},
		{
			MethodName: "UniV3Swaps",
			Handler:    _EVM_UniV3Swaps_Handler,
		},
		{
			MethodName: "ERC20TransferEvents",
			Handler:    _EVM_ERC20TransferEvents_Handler,
		},
		{
			MethodName: "ERC20ApprovalEvents",
			Handler:    _EVM_ERC20ApprovalEvents_Handler,
		},
		{
			MethodName: "UniCandles",
			Handler:    _EVM_UniCandles_Handler,
		},
		{
			MethodName: "HpumpV1LaunchToken",
			Handler:    _EVM_HpumpV1LaunchToken_Handler,
		},
		{
			MethodName: "HpumpV1LaunchTokens",
			Handler:    _EVM_HpumpV1LaunchTokens_Handler,
		},
		{
			MethodName: "HpumpV1LaunchPair",
			Handler:    _EVM_HpumpV1LaunchPair_Handler,
		},
		{
			MethodName: "HpumpV1LaunchPairs",
			Handler:    _EVM_HpumpV1LaunchPairs_Handler,
		},
		{
			MethodName: "HpumpV1LaunchPairSwap",
			Handler:    _EVM_HpumpV1LaunchPairSwap_Handler,
		},
		{
			MethodName: "HpumpV1LaunchPairSwaps",
			Handler:    _EVM_HpumpV1LaunchPairSwaps_Handler,
		},
		{
			MethodName: "HpumpV1",
			Handler:    _EVM_HpumpV1_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UniV2SwapStream",
			Handler:       _EVM_UniV2SwapStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UniV3SwapStream",
			Handler:       _EVM_UniV3SwapStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "HpumpV1LaunchPairSwapStream",
			Handler:       _EVM_HpumpV1LaunchPairSwapStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "hypurr/evm_service.proto",
}
