# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hypurr import ios_pb2 as hypurr_dot_ios__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hypurr/ios_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IosServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Home = channel.unary_unary(
                '/hypurr.IosService/Home',
                request_serializer=hypurr_dot_ios__pb2.HomeRequest.SerializeToString,
                response_deserializer=hypurr_dot_ios__pb2.HomeResponse.FromString,
                _registered_method=True)
        self.AssetDetail = channel.unary_unary(
                '/hypurr.IosService/AssetDetail',
                request_serializer=hypurr_dot_ios__pb2.AssetDetailRequest.SerializeToString,
                response_deserializer=hypurr_dot_ios__pb2.AssetDetailResponse.FromString,
                _registered_method=True)
        self.AssetDetailLiveUpdates = channel.unary_stream(
                '/hypurr.IosService/AssetDetailLiveUpdates',
                request_serializer=hypurr_dot_ios__pb2.AssetDetailLiveUpdatesRequest.SerializeToString,
                response_deserializer=hypurr_dot_ios__pb2.AssetDetailLiveUpdate.FromString,
                _registered_method=True)
        self.AssetMetadataCatalog = channel.unary_unary(
                '/hypurr.IosService/AssetMetadataCatalog',
                request_serializer=hypurr_dot_ios__pb2.AssetMetadataCatalogRequest.SerializeToString,
                response_deserializer=hypurr_dot_ios__pb2.AssetMetadataCatalogResponse.FromString,
                _registered_method=True)
        self.Accounts = channel.unary_unary(
                '/hypurr.IosService/Accounts',
                request_serializer=hypurr_dot_ios__pb2.AccountsRequest.SerializeToString,
                response_deserializer=hypurr_dot_ios__pb2.AccountsResponse.FromString,
                _registered_method=True)
        self.Profile = channel.unary_unary(
                '/hypurr.IosService/Profile',
                request_serializer=hypurr_dot_ios__pb2.ProfileRequest.SerializeToString,
                response_deserializer=hypurr_dot_ios__pb2.ProfileResponse.FromString,
                _registered_method=True)
        self.UserStream = channel.unary_stream(
                '/hypurr.IosService/UserStream',
                request_serializer=hypurr_dot_ios__pb2.UserStreamRequest.SerializeToString,
                response_deserializer=hypurr_dot_ios__pb2.UserSnapshot.FromString,
                _registered_method=True)


class IosServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Home(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssetDetail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssetDetailLiveUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssetMetadataCatalog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Accounts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Profile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IosServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Home': grpc.unary_unary_rpc_method_handler(
                    servicer.Home,
                    request_deserializer=hypurr_dot_ios__pb2.HomeRequest.FromString,
                    response_serializer=hypurr_dot_ios__pb2.HomeResponse.SerializeToString,
            ),
            'AssetDetail': grpc.unary_unary_rpc_method_handler(
                    servicer.AssetDetail,
                    request_deserializer=hypurr_dot_ios__pb2.AssetDetailRequest.FromString,
                    response_serializer=hypurr_dot_ios__pb2.AssetDetailResponse.SerializeToString,
            ),
            'AssetDetailLiveUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.AssetDetailLiveUpdates,
                    request_deserializer=hypurr_dot_ios__pb2.AssetDetailLiveUpdatesRequest.FromString,
                    response_serializer=hypurr_dot_ios__pb2.AssetDetailLiveUpdate.SerializeToString,
            ),
            'AssetMetadataCatalog': grpc.unary_unary_rpc_method_handler(
                    servicer.AssetMetadataCatalog,
                    request_deserializer=hypurr_dot_ios__pb2.AssetMetadataCatalogRequest.FromString,
                    response_serializer=hypurr_dot_ios__pb2.AssetMetadataCatalogResponse.SerializeToString,
            ),
            'Accounts': grpc.unary_unary_rpc_method_handler(
                    servicer.Accounts,
                    request_deserializer=hypurr_dot_ios__pb2.AccountsRequest.FromString,
                    response_serializer=hypurr_dot_ios__pb2.AccountsResponse.SerializeToString,
            ),
            'Profile': grpc.unary_unary_rpc_method_handler(
                    servicer.Profile,
                    request_deserializer=hypurr_dot_ios__pb2.ProfileRequest.FromString,
                    response_serializer=hypurr_dot_ios__pb2.ProfileResponse.SerializeToString,
            ),
            'UserStream': grpc.unary_stream_rpc_method_handler(
                    servicer.UserStream,
                    request_deserializer=hypurr_dot_ios__pb2.UserStreamRequest.FromString,
                    response_serializer=hypurr_dot_ios__pb2.UserSnapshot.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hypurr.IosService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hypurr.IosService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IosService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Home(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypurr.IosService/Home',
            hypurr_dot_ios__pb2.HomeRequest.SerializeToString,
            hypurr_dot_ios__pb2.HomeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssetDetail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypurr.IosService/AssetDetail',
            hypurr_dot_ios__pb2.AssetDetailRequest.SerializeToString,
            hypurr_dot_ios__pb2.AssetDetailResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssetDetailLiveUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hypurr.IosService/AssetDetailLiveUpdates',
            hypurr_dot_ios__pb2.AssetDetailLiveUpdatesRequest.SerializeToString,
            hypurr_dot_ios__pb2.AssetDetailLiveUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssetMetadataCatalog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypurr.IosService/AssetMetadataCatalog',
            hypurr_dot_ios__pb2.AssetMetadataCatalogRequest.SerializeToString,
            hypurr_dot_ios__pb2.AssetMetadataCatalogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Accounts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypurr.IosService/Accounts',
            hypurr_dot_ios__pb2.AccountsRequest.SerializeToString,
            hypurr_dot_ios__pb2.AccountsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Profile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypurr.IosService/Profile',
            hypurr_dot_ios__pb2.ProfileRequest.SerializeToString,
            hypurr_dot_ios__pb2.ProfileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hypurr.IosService/UserStream',
            hypurr_dot_ios__pb2.UserStreamRequest.SerializeToString,
            hypurr_dot_ios__pb2.UserSnapshot.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
