# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from hypurr import kms_pb2 as hypurr_dot_kms__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hypurr/kms_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KmsStub:
    """Kms forwards sealed payloads between the app and the hfun-kms instance;
    the bot cannot read or alter them.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAttestation = channel.unary_unary(
                '/hypurr.Kms/GetAttestation',
                request_serializer=hypurr_dot_kms__pb2.KmsGetAttestationRequest.SerializeToString,
                response_deserializer=hypurr_dot_kms__pb2.KmsGetAttestationResponse.FromString,
                _registered_method=True)
        self.LoginOrRegister = channel.unary_unary(
                '/hypurr.Kms/LoginOrRegister',
                request_serializer=hypurr_dot_kms__pb2.KmsLoginOrRegisterRequest.SerializeToString,
                response_deserializer=hypurr_dot_kms__pb2.KmsLoginOrRegisterResponse.FromString,
                _registered_method=True)
        self.LoginIntent = channel.unary_unary(
                '/hypurr.Kms/LoginIntent',
                request_serializer=hypurr_dot_kms__pb2.KmsLoginIntentRequest.SerializeToString,
                response_deserializer=hypurr_dot_kms__pb2.KmsLoginIntentResponse.FromString,
                _registered_method=True)
        self.AddProvider = channel.unary_unary(
                '/hypurr.Kms/AddProvider',
                request_serializer=hypurr_dot_kms__pb2.KmsAddProviderRequest.SerializeToString,
                response_deserializer=hypurr_dot_kms__pb2.KmsAddProviderResponse.FromString,
                _registered_method=True)
        self.AccountEnable2FA = channel.unary_unary(
                '/hypurr.Kms/AccountEnable2FA',
                request_serializer=hypurr_dot_kms__pb2.KmsAccountEnable2FARequest.SerializeToString,
                response_deserializer=hypurr_dot_kms__pb2.KmsAccountEnable2FAResponse.FromString,
                _registered_method=True)
        self.AccountDisable2FA = channel.unary_unary(
                '/hypurr.Kms/AccountDisable2FA',
                request_serializer=hypurr_dot_kms__pb2.KmsAccountDisable2FARequest.SerializeToString,
                response_deserializer=hypurr_dot_kms__pb2.KmsAccountDisable2FAResponse.FromString,
                _registered_method=True)
        self.AccountShardSecret = channel.unary_unary(
                '/hypurr.Kms/AccountShardSecret',
                request_serializer=hypurr_dot_kms__pb2.KmsAccountShardSecretRequest.SerializeToString,
                response_deserializer=hypurr_dot_kms__pb2.KmsAccountShardSecretResponse.FromString,
                _registered_method=True)
        self.AccountSignMessage = channel.unary_unary(
                '/hypurr.Kms/AccountSignMessage',
                request_serializer=hypurr_dot_kms__pb2.KmsAccountSignMessageRequest.SerializeToString,
                response_deserializer=hypurr_dot_kms__pb2.KmsAccountSignMessageResponse.FromString,
                _registered_method=True)
        self.AccountApproveAgent = channel.unary_unary(
                '/hypurr.Kms/AccountApproveAgent',
                request_serializer=hypurr_dot_kms__pb2.KmsAccountApproveAgentRequest.SerializeToString,
                response_deserializer=hypurr_dot_kms__pb2.KmsAccountApproveAgentResponse.FromString,
                _registered_method=True)
        self.GetAccountInfo = channel.unary_unary(
                '/hypurr.Kms/GetAccountInfo',
                request_serializer=hypurr_dot_kms__pb2.KmsGetAccountInfoRequest.SerializeToString,
                response_deserializer=hypurr_dot_kms__pb2.KmsGetAccountInfoResponse.FromString,
                _registered_method=True)
        self.RequestFactorReset = channel.unary_unary(
                '/hypurr.Kms/RequestFactorReset',
                request_serializer=hypurr_dot_kms__pb2.KmsRequestFactorResetRequest.SerializeToString,
                response_deserializer=hypurr_dot_kms__pb2.KmsRequestFactorResetResponse.FromString,
                _registered_method=True)
        self.CancelFactorReset = channel.unary_unary(
                '/hypurr.Kms/CancelFactorReset',
                request_serializer=hypurr_dot_kms__pb2.KmsCancelFactorResetRequest.SerializeToString,
                response_deserializer=hypurr_dot_kms__pb2.KmsCancelFactorResetResponse.FromString,
                _registered_method=True)
        self.ExecuteFactorReset = channel.unary_unary(
                '/hypurr.Kms/ExecuteFactorReset',
                request_serializer=hypurr_dot_kms__pb2.KmsExecuteFactorResetRequest.SerializeToString,
                response_deserializer=hypurr_dot_kms__pb2.KmsExecuteFactorResetResponse.FromString,
                _registered_method=True)
        self.RecoverKeys = channel.unary_unary(
                '/hypurr.Kms/RecoverKeys',
                request_serializer=hypurr_dot_kms__pb2.KmsRecoverKeysRequest.SerializeToString,
                response_deserializer=hypurr_dot_kms__pb2.KmsRecoverKeysResponse.FromString,
                _registered_method=True)
        self.CompleteAccountHandoff = channel.unary_unary(
                '/hypurr.Kms/CompleteAccountHandoff',
                request_serializer=hypurr_dot_kms__pb2.KmsCompleteAccountHandoffRequest.SerializeToString,
                response_deserializer=hypurr_dot_kms__pb2.KmsCompleteAccountHandoffResponse.FromString,
                _registered_method=True)
        self.RequestAgent = channel.unary_unary(
                '/hypurr.Kms/RequestAgent',
                request_serializer=hypurr_dot_kms__pb2.KmsRequestAgentRequest.SerializeToString,
                response_deserializer=hypurr_dot_kms__pb2.KmsRequestAgentResponse.FromString,
                _registered_method=True)


class KmsServicer:
    """Kms forwards sealed payloads between the app and the hfun-kms instance;
    the bot cannot read or alter them.
    """

    def GetAttestation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginOrRegister(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginIntent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddProvider(self, request, context):
        """Routed by the instance JWT.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AccountEnable2FA(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AccountDisable2FA(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AccountShardSecret(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AccountSignMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AccountApproveAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAccountInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestFactorReset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelFactorReset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteFactorReset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecoverKeys(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteAccountHandoff(self, request, context):
        """Bot JWT.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KmsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAttestation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttestation,
                    request_deserializer=hypurr_dot_kms__pb2.KmsGetAttestationRequest.FromString,
                    response_serializer=hypurr_dot_kms__pb2.KmsGetAttestationResponse.SerializeToString,
            ),
            'LoginOrRegister': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginOrRegister,
                    request_deserializer=hypurr_dot_kms__pb2.KmsLoginOrRegisterRequest.FromString,
                    response_serializer=hypurr_dot_kms__pb2.KmsLoginOrRegisterResponse.SerializeToString,
            ),
            'LoginIntent': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginIntent,
                    request_deserializer=hypurr_dot_kms__pb2.KmsLoginIntentRequest.FromString,
                    response_serializer=hypurr_dot_kms__pb2.KmsLoginIntentResponse.SerializeToString,
            ),
            'AddProvider': grpc.unary_unary_rpc_method_handler(
                    servicer.AddProvider,
                    request_deserializer=hypurr_dot_kms__pb2.KmsAddProviderRequest.FromString,
                    response_serializer=hypurr_dot_kms__pb2.KmsAddProviderResponse.SerializeToString,
            ),
            'AccountEnable2FA': grpc.unary_unary_rpc_method_handler(
                    servicer.AccountEnable2FA,
                    request_deserializer=hypurr_dot_kms__pb2.KmsAccountEnable2FARequest.FromString,
                    response_serializer=hypurr_dot_kms__pb2.KmsAccountEnable2FAResponse.SerializeToString,
            ),
            'AccountDisable2FA': grpc.unary_unary_rpc_method_handler(
                    servicer.AccountDisable2FA,
                    request_deserializer=hypurr_dot_kms__pb2.KmsAccountDisable2FARequest.FromString,
                    response_serializer=hypurr_dot_kms__pb2.KmsAccountDisable2FAResponse.SerializeToString,
            ),
            'AccountShardSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.AccountShardSecret,
                    request_deserializer=hypurr_dot_kms__pb2.KmsAccountShardSecretRequest.FromString,
                    response_serializer=hypurr_dot_kms__pb2.KmsAccountShardSecretResponse.SerializeToString,
            ),
            'AccountSignMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.AccountSignMessage,
                    request_deserializer=hypurr_dot_kms__pb2.KmsAccountSignMessageRequest.FromString,
                    response_serializer=hypurr_dot_kms__pb2.KmsAccountSignMessageResponse.SerializeToString,
            ),
            'AccountApproveAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.AccountApproveAgent,
                    request_deserializer=hypurr_dot_kms__pb2.KmsAccountApproveAgentRequest.FromString,
                    response_serializer=hypurr_dot_kms__pb2.KmsAccountApproveAgentResponse.SerializeToString,
            ),
            'GetAccountInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAccountInfo,
                    request_deserializer=hypurr_dot_kms__pb2.KmsGetAccountInfoRequest.FromString,
                    response_serializer=hypurr_dot_kms__pb2.KmsGetAccountInfoResponse.SerializeToString,
            ),
            'RequestFactorReset': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestFactorReset,
                    request_deserializer=hypurr_dot_kms__pb2.KmsRequestFactorResetRequest.FromString,
                    response_serializer=hypurr_dot_kms__pb2.KmsRequestFactorResetResponse.SerializeToString,
            ),
            'CancelFactorReset': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelFactorReset,
                    request_deserializer=hypurr_dot_kms__pb2.KmsCancelFactorResetRequest.FromString,
                    response_serializer=hypurr_dot_kms__pb2.KmsCancelFactorResetResponse.SerializeToString,
            ),
            'ExecuteFactorReset': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteFactorReset,
                    request_deserializer=hypurr_dot_kms__pb2.KmsExecuteFactorResetRequest.FromString,
                    response_serializer=hypurr_dot_kms__pb2.KmsExecuteFactorResetResponse.SerializeToString,
            ),
            'RecoverKeys': grpc.unary_unary_rpc_method_handler(
                    servicer.RecoverKeys,
                    request_deserializer=hypurr_dot_kms__pb2.KmsRecoverKeysRequest.FromString,
                    response_serializer=hypurr_dot_kms__pb2.KmsRecoverKeysResponse.SerializeToString,
            ),
            'CompleteAccountHandoff': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteAccountHandoff,
                    request_deserializer=hypurr_dot_kms__pb2.KmsCompleteAccountHandoffRequest.FromString,
                    response_serializer=hypurr_dot_kms__pb2.KmsCompleteAccountHandoffResponse.SerializeToString,
            ),
            'RequestAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestAgent,
                    request_deserializer=hypurr_dot_kms__pb2.KmsRequestAgentRequest.FromString,
                    response_serializer=hypurr_dot_kms__pb2.KmsRequestAgentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hypurr.Kms', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hypurr.Kms', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Kms:
    """Kms forwards sealed payloads between the app and the hfun-kms instance;
    the bot cannot read or alter them.
    """

    @staticmethod
    def GetAttestation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypurr.Kms/GetAttestation',
            hypurr_dot_kms__pb2.KmsGetAttestationRequest.SerializeToString,
            hypurr_dot_kms__pb2.KmsGetAttestationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoginOrRegister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypurr.Kms/LoginOrRegister',
            hypurr_dot_kms__pb2.KmsLoginOrRegisterRequest.SerializeToString,
            hypurr_dot_kms__pb2.KmsLoginOrRegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoginIntent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypurr.Kms/LoginIntent',
            hypurr_dot_kms__pb2.KmsLoginIntentRequest.SerializeToString,
            hypurr_dot_kms__pb2.KmsLoginIntentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddProvider(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypurr.Kms/AddProvider',
            hypurr_dot_kms__pb2.KmsAddProviderRequest.SerializeToString,
            hypurr_dot_kms__pb2.KmsAddProviderResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AccountEnable2FA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypurr.Kms/AccountEnable2FA',
            hypurr_dot_kms__pb2.KmsAccountEnable2FARequest.SerializeToString,
            hypurr_dot_kms__pb2.KmsAccountEnable2FAResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AccountDisable2FA(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypurr.Kms/AccountDisable2FA',
            hypurr_dot_kms__pb2.KmsAccountDisable2FARequest.SerializeToString,
            hypurr_dot_kms__pb2.KmsAccountDisable2FAResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AccountShardSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypurr.Kms/AccountShardSecret',
            hypurr_dot_kms__pb2.KmsAccountShardSecretRequest.SerializeToString,
            hypurr_dot_kms__pb2.KmsAccountShardSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AccountSignMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypurr.Kms/AccountSignMessage',
            hypurr_dot_kms__pb2.KmsAccountSignMessageRequest.SerializeToString,
            hypurr_dot_kms__pb2.KmsAccountSignMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AccountApproveAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypurr.Kms/AccountApproveAgent',
            hypurr_dot_kms__pb2.KmsAccountApproveAgentRequest.SerializeToString,
            hypurr_dot_kms__pb2.KmsAccountApproveAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAccountInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypurr.Kms/GetAccountInfo',
            hypurr_dot_kms__pb2.KmsGetAccountInfoRequest.SerializeToString,
            hypurr_dot_kms__pb2.KmsGetAccountInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestFactorReset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypurr.Kms/RequestFactorReset',
            hypurr_dot_kms__pb2.KmsRequestFactorResetRequest.SerializeToString,
            hypurr_dot_kms__pb2.KmsRequestFactorResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelFactorReset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypurr.Kms/CancelFactorReset',
            hypurr_dot_kms__pb2.KmsCancelFactorResetRequest.SerializeToString,
            hypurr_dot_kms__pb2.KmsCancelFactorResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecuteFactorReset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypurr.Kms/ExecuteFactorReset',
            hypurr_dot_kms__pb2.KmsExecuteFactorResetRequest.SerializeToString,
            hypurr_dot_kms__pb2.KmsExecuteFactorResetResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecoverKeys(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypurr.Kms/RecoverKeys',
            hypurr_dot_kms__pb2.KmsRecoverKeysRequest.SerializeToString,
            hypurr_dot_kms__pb2.KmsRecoverKeysResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteAccountHandoff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypurr.Kms/CompleteAccountHandoff',
            hypurr_dot_kms__pb2.KmsCompleteAccountHandoffRequest.SerializeToString,
            hypurr_dot_kms__pb2.KmsCompleteAccountHandoffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hypurr.Kms/RequestAgent',
            hypurr_dot_kms__pb2.KmsRequestAgentRequest.SerializeToString,
            hypurr_dot_kms__pb2.KmsRequestAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
