# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hypurr/hyperevm/hyperevm_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='hypurr/hyperevm/hyperevm_service.proto',
  package='hyperevm',
  syntax='proto3',
  serialized_pb=_b('\n&hypurr/hyperevm/hyperevm_service.proto\x12\x08hyperevm\x1a\x1egoogle/protobuf/wrappers.proto\"\'\n\x14TokenBalancesRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\"G\n\x15TokenBalancesResponse\x12.\n\x0etoken_balances\x18\x01 \x03(\x0b\x32\x16.hyperevm.TokenBalance\"9\n\x0cTokenBalance\x12\x18\n\x10\x63ontract_address\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x01\x32^\n\x08HyperEvm\x12R\n\rTokenBalances\x12\x1e.hyperevm.TokenBalancesRequest\x1a\x1f.hyperevm.TokenBalancesResponse\"\x00\x42\x32Z0gitlab.com/hypurr/hypurr-grpc/go/hypurr/hyperevmb\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])




_TOKENBALANCESREQUEST = _descriptor.Descriptor(
  name='TokenBalancesRequest',
  full_name='hyperevm.TokenBalancesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='hyperevm.TokenBalancesRequest.address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=123,
)


_TOKENBALANCESRESPONSE = _descriptor.Descriptor(
  name='TokenBalancesResponse',
  full_name='hyperevm.TokenBalancesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token_balances', full_name='hyperevm.TokenBalancesResponse.token_balances', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=196,
)


_TOKENBALANCE = _descriptor.Descriptor(
  name='TokenBalance',
  full_name='hyperevm.TokenBalance',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='contract_address', full_name='hyperevm.TokenBalance.contract_address', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='balance', full_name='hyperevm.TokenBalance.balance', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=255,
)

_TOKENBALANCESRESPONSE.fields_by_name['token_balances'].message_type = _TOKENBALANCE
DESCRIPTOR.message_types_by_name['TokenBalancesRequest'] = _TOKENBALANCESREQUEST
DESCRIPTOR.message_types_by_name['TokenBalancesResponse'] = _TOKENBALANCESRESPONSE
DESCRIPTOR.message_types_by_name['TokenBalance'] = _TOKENBALANCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TokenBalancesRequest = _reflection.GeneratedProtocolMessageType('TokenBalancesRequest', (_message.Message,), dict(
  DESCRIPTOR = _TOKENBALANCESREQUEST,
  __module__ = 'hypurr.hyperevm.hyperevm_service_pb2'
  # @@protoc_insertion_point(class_scope:hyperevm.TokenBalancesRequest)
  ))
_sym_db.RegisterMessage(TokenBalancesRequest)

TokenBalancesResponse = _reflection.GeneratedProtocolMessageType('TokenBalancesResponse', (_message.Message,), dict(
  DESCRIPTOR = _TOKENBALANCESRESPONSE,
  __module__ = 'hypurr.hyperevm.hyperevm_service_pb2'
  # @@protoc_insertion_point(class_scope:hyperevm.TokenBalancesResponse)
  ))
_sym_db.RegisterMessage(TokenBalancesResponse)

TokenBalance = _reflection.GeneratedProtocolMessageType('TokenBalance', (_message.Message,), dict(
  DESCRIPTOR = _TOKENBALANCE,
  __module__ = 'hypurr.hyperevm.hyperevm_service_pb2'
  # @@protoc_insertion_point(class_scope:hyperevm.TokenBalance)
  ))
_sym_db.RegisterMessage(TokenBalance)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z0gitlab.com/hypurr/hypurr-grpc/go/hypurr/hyperevm'))

_HYPEREVM = _descriptor.ServiceDescriptor(
  name='HyperEvm',
  full_name='hyperevm.HyperEvm',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=257,
  serialized_end=351,
  methods=[
  _descriptor.MethodDescriptor(
    name='TokenBalances',
    full_name='hyperevm.HyperEvm.TokenBalances',
    index=0,
    containing_service=None,
    input_type=_TOKENBALANCESREQUEST,
    output_type=_TOKENBALANCESRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HYPEREVM)

DESCRIPTOR.services_by_name['HyperEvm'] = _HYPEREVM

# @@protoc_insertion_point(module_scope)
