# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from hypurr.telegram import telegram_service_pb2 as hypurr_dot_telegram_dot_telegram__service__pb2


class TelegramStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.TelegramUser = channel.unary_unary(
        '/hypurr.Telegram/TelegramUser',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramUserRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramUserResponse.FromString,
        )
    self.TelegramAuthExchange = channel.unary_unary(
        '/hypurr.Telegram/TelegramAuthExchange',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramAuthExchangeRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramAuthExchangeResponse.FromString,
        )
    self.TelegramUserWallets = channel.unary_unary(
        '/hypurr.Telegram/TelegramUserWallets',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramUserWalletsRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramUserWalletsResponse.FromString,
        )
    self.HyperliquidMostTrackedWallets = channel.unary_unary(
        '/hypurr.Telegram/HyperliquidMostTrackedWallets',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidMostTrackedWalletsRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidMostTrackedWalletsResponse.FromString,
        )
    self.HyperliquidLaunchTrade = channel.unary_unary(
        '/hypurr.Telegram/HyperliquidLaunchTrade',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidLaunchTradeRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidLaunchTradeResponse.FromString,
        )
    self.LaunchHyperliquidLaunch = channel.unary_unary(
        '/hypurr.Telegram/LaunchHyperliquidLaunch',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.LaunchHyperliquidLaunchRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.LaunchHyperliquidLaunchResponse.FromString,
        )
    self.EditHyperliquidLaunch = channel.unary_unary(
        '/hypurr.Telegram/EditHyperliquidLaunch',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.EditHyperliquidLaunchRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.EditHyperliquidLaunchResponse.FromString,
        )
    self.HpumpV1LaunchTrade = channel.unary_unary(
        '/hypurr.Telegram/HpumpV1LaunchTrade',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HpumpV1LaunchTradeRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HpumpV1LaunchTradeResponse.FromString,
        )
    self.LaunchHpumpV1Launch = channel.unary_unary(
        '/hypurr.Telegram/LaunchHpumpV1Launch',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.LaunchHpumpV1LaunchRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.LaunchHpumpV1LaunchResponse.FromString,
        )
    self.HyperliquidCoreAction = channel.unary_unary(
        '/hypurr.Telegram/HyperliquidCoreAction',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidCoreActionRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidCoreActionResponse.FromString,
        )
    self.HyperliquidSpotTrade = channel.unary_unary(
        '/hypurr.Telegram/HyperliquidSpotTrade',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidSpotTradeRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidSpotTradeResponse.FromString,
        )
    self.HyperliquidCoreTrade = channel.unary_unary(
        '/hypurr.Telegram/HyperliquidCoreTrade',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidCoreTradeRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidCoreTradeResponse.FromString,
        )
    self.HyperliquidCoreCancelOrders = channel.unary_unary(
        '/hypurr.Telegram/HyperliquidCoreCancelOrders',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidCoreCancelOrdersRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidCoreCancelOrdersResponse.FromString,
        )
    self.HyperliquidWalletSpotTwapSessions = channel.unary_unary(
        '/hypurr.Telegram/HyperliquidWalletSpotTwapSessions',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletSpotTwapSessionsRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletSpotTwapSessionsResponse.FromString,
        )
    self.HyperliquidWalletTwapSessions = channel.unary_unary(
        '/hypurr.Telegram/HyperliquidWalletTwapSessions',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletTwapSessionsRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletTwapSessionsResponse.FromString,
        )
    self.HyperliquidWalletScaleSessions = channel.unary_unary(
        '/hypurr.Telegram/HyperliquidWalletScaleSessions',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletScaleSessionsRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletScaleSessionsResponse.FromString,
        )
    self.HyperliquidTwapCreate = channel.unary_unary(
        '/hypurr.Telegram/HyperliquidTwapCreate',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidTwapCreateRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidTwapCreateResponse.FromString,
        )
    self.HyperliquidTwapModify = channel.unary_unary(
        '/hypurr.Telegram/HyperliquidTwapModify',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidTwapModifyRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidTwapModifyResponse.FromString,
        )
    self.HyperliquidTwapCancel = channel.unary_unary(
        '/hypurr.Telegram/HyperliquidTwapCancel',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidTwapCancelRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidTwapCancelResponse.FromString,
        )
    self.HyperliquidScaleCreate = channel.unary_unary(
        '/hypurr.Telegram/HyperliquidScaleCreate',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidScaleCreateRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidScaleCreateResponse.FromString,
        )
    self.HyperliquidScaleCancel = channel.unary_unary(
        '/hypurr.Telegram/HyperliquidScaleCancel',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidScaleCancelRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidScaleCancelResponse.FromString,
        )
    self.HyperliquidSpotSniperConfigs = channel.unary_unary(
        '/hypurr.Telegram/HyperliquidSpotSniperConfigs',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidSpotSniperConfigsRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidSpotSniperConfigsResponse.FromString,
        )
    self.CreateHyperliquidSpotSniperConfig = channel.unary_unary(
        '/hypurr.Telegram/CreateHyperliquidSpotSniperConfig',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.CreateHyperliquidSpotSniperConfigRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.CreateHyperliquidSpotSniperConfigResponse.FromString,
        )
    self.DeleteHyperliquidSpotSniperConfig = channel.unary_unary(
        '/hypurr.Telegram/DeleteHyperliquidSpotSniperConfig',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.DeleteHyperliquidSpotSniperConfigRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.DeleteHyperliquidSpotSniperConfigResponse.FromString,
        )
    self.UpdateHyperliquidSpotSniperConfig = channel.unary_unary(
        '/hypurr.Telegram/UpdateHyperliquidSpotSniperConfig',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.UpdateHyperliquidSpotSniperConfigRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.UpdateHyperliquidSpotSniperConfigResponse.FromString,
        )
    self.HyperliquidWalletCreate = channel.unary_unary(
        '/hypurr.Telegram/HyperliquidWalletCreate',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletCreateRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletCreateResponse.FromString,
        )
    self.HyperliquidWalletDelete = channel.unary_unary(
        '/hypurr.Telegram/HyperliquidWalletDelete',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletDeleteRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletDeleteResponse.FromString,
        )
    self.HyperliquidWalletSetPublic = channel.unary_unary(
        '/hypurr.Telegram/HyperliquidWalletSetPublic',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletSetPublicRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletSetPublicResponse.FromString,
        )
    self.HyperliquidAgentSignatureCreate = channel.unary_unary(
        '/hypurr.Telegram/HyperliquidAgentSignatureCreate',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidAgentSignatureCreateRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidAgentSignatureCreateResponse.FromString,
        )
    self.HyperliquidAgentWalletCreate = channel.unary_unary(
        '/hypurr.Telegram/HyperliquidAgentWalletCreate',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidAgentWalletCreateRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidAgentWalletCreateResponse.FromString,
        )
    self.HyperliquidWalletUpdate = channel.unary_unary(
        '/hypurr.Telegram/HyperliquidWalletUpdate',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletUpdateRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletUpdateResponse.FromString,
        )
    self.HfunCabalAlerts = channel.unary_stream(
        '/hypurr.Telegram/HfunCabalAlerts',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HfunCabalAlertsRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HfunCabalAlertsResponse.FromString,
        )
    self.TelegramChatWalletPackCreate = channel.unary_unary(
        '/hypurr.Telegram/TelegramChatWalletPackCreate',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramChatWalletPackCreateRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramChatWalletPackCreateResponse.FromString,
        )
    self.TelegramChatWalletPackRename = channel.unary_unary(
        '/hypurr.Telegram/TelegramChatWalletPackRename',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramChatWalletPackRenameRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramChatWalletPackRenameResponse.FromString,
        )
    self.TelegramChatWalletPackLabelAdd = channel.unary_unary(
        '/hypurr.Telegram/TelegramChatWalletPackLabelAdd',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramChatWalletPackLabelAddRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramChatWalletPackLabelAddResponse.FromString,
        )
    self.TelegramChatWalletPackLabelModify = channel.unary_unary(
        '/hypurr.Telegram/TelegramChatWalletPackLabelModify',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramChatWalletPackLabelModifyRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramChatWalletPackLabelModifyResponse.FromString,
        )
    self.TelegramChatWalletPackLabelRemove = channel.unary_unary(
        '/hypurr.Telegram/TelegramChatWalletPackLabelRemove',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramChatWalletPackLabelDeleteRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramChatWalletPackLabelDeleteResponse.FromString,
        )
    self.SupportConversationStart = channel.unary_unary(
        '/hypurr.Telegram/SupportConversationStart',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportConversationStartRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportConversationStartResponse.FromString,
        )
    self.SupportMessageSend = channel.unary_unary(
        '/hypurr.Telegram/SupportMessageSend',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportMessageSendRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportMessageSendResponse.FromString,
        )
    self.SupportConversationHistory = channel.unary_unary(
        '/hypurr.Telegram/SupportConversationHistory',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportConversationHistoryRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportConversationHistoryResponse.FromString,
        )
    self.SupportConversationList = channel.unary_unary(
        '/hypurr.Telegram/SupportConversationList',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportConversationListRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportConversationListResponse.FromString,
        )
    self.SupportConversationClose = channel.unary_unary(
        '/hypurr.Telegram/SupportConversationClose',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportConversationCloseRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportConversationCloseResponse.FromString,
        )
    self.SupportTicketStatus = channel.unary_unary(
        '/hypurr.Telegram/SupportTicketStatus',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportTicketStatusRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportTicketStatusResponse.FromString,
        )
    self.GetPortfolioAllocator = channel.unary_unary(
        '/hypurr.Telegram/GetPortfolioAllocator',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.GetPortfolioAllocatorRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.GetPortfolioAllocatorResponse.FromString,
        )
    self.ListPortfolioAllocators = channel.unary_unary(
        '/hypurr.Telegram/ListPortfolioAllocators',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.ListPortfolioAllocatorsRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.ListPortfolioAllocatorsResponse.FromString,
        )
    self.ListEnabledPortfolioAllocators = channel.unary_unary(
        '/hypurr.Telegram/ListEnabledPortfolioAllocators',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.ListEnabledPortfolioAllocatorsRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.ListEnabledPortfolioAllocatorsResponse.FromString,
        )
    self.GetPortfolioSource = channel.unary_unary(
        '/hypurr.Telegram/GetPortfolioSource',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.GetPortfolioSourceRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.GetPortfolioSourceResponse.FromString,
        )
    self.ListPortfolioSources = channel.unary_unary(
        '/hypurr.Telegram/ListPortfolioSources',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.ListPortfolioSourcesRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.ListPortfolioSourcesResponse.FromString,
        )
    self.CreatePortfolioAllocator = channel.unary_unary(
        '/hypurr.Telegram/CreatePortfolioAllocator',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.CreatePortfolioAllocatorRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.CreatePortfolioAllocatorResponse.FromString,
        )
    self.UpdatePortfolioAllocator = channel.unary_unary(
        '/hypurr.Telegram/UpdatePortfolioAllocator',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.UpdatePortfolioAllocatorRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.UpdatePortfolioAllocatorResponse.FromString,
        )
    self.DeletePortfolioAllocator = channel.unary_unary(
        '/hypurr.Telegram/DeletePortfolioAllocator',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.DeletePortfolioAllocatorRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.DeletePortfolioAllocatorResponse.FromString,
        )
    self.CreatePortfolioSource = channel.unary_unary(
        '/hypurr.Telegram/CreatePortfolioSource',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.CreatePortfolioSourceRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.CreatePortfolioSourceResponse.FromString,
        )
    self.UpdatePortfolioSource = channel.unary_unary(
        '/hypurr.Telegram/UpdatePortfolioSource',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.UpdatePortfolioSourceRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.UpdatePortfolioSourceResponse.FromString,
        )
    self.DeletePortfolioSource = channel.unary_unary(
        '/hypurr.Telegram/DeletePortfolioSource',
        request_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.DeletePortfolioSourceRequest.SerializeToString,
        response_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.DeletePortfolioSourceResponse.FromString,
        )


class TelegramServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def TelegramUser(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TelegramAuthExchange(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TelegramUserWallets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HyperliquidMostTrackedWallets(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HyperliquidLaunchTrade(self, request, context):
    """Launch
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LaunchHyperliquidLaunch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EditHyperliquidLaunch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HpumpV1LaunchTrade(self, request, context):
    """HpumpV1
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def LaunchHpumpV1Launch(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HyperliquidCoreAction(self, request, context):
    """Core
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HyperliquidSpotTrade(self, request, context):
    """Spot
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HyperliquidCoreTrade(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HyperliquidCoreCancelOrders(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HyperliquidWalletSpotTwapSessions(self, request, context):
    """Sessions
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HyperliquidWalletTwapSessions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HyperliquidWalletScaleSessions(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HyperliquidTwapCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HyperliquidTwapModify(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HyperliquidTwapCancel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HyperliquidScaleCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HyperliquidScaleCancel(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HyperliquidSpotSniperConfigs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreateHyperliquidSpotSniperConfig(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteHyperliquidSpotSniperConfig(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdateHyperliquidSpotSniperConfig(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HyperliquidWalletCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HyperliquidWalletDelete(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HyperliquidWalletSetPublic(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HyperliquidAgentSignatureCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HyperliquidAgentWalletCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HyperliquidWalletUpdate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HfunCabalAlerts(self, request, context):
    """Cabal
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TelegramChatWalletPackCreate(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TelegramChatWalletPackRename(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TelegramChatWalletPackLabelAdd(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TelegramChatWalletPackLabelModify(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def TelegramChatWalletPackLabelRemove(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SupportConversationStart(self, request, context):
    """Support
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SupportMessageSend(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SupportConversationHistory(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SupportConversationList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SupportConversationClose(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SupportTicketStatus(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPortfolioAllocator(self, request, context):
    """Portfolio
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListPortfolioAllocators(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListEnabledPortfolioAllocators(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetPortfolioSource(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListPortfolioSources(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreatePortfolioAllocator(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdatePortfolioAllocator(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeletePortfolioAllocator(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CreatePortfolioSource(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def UpdatePortfolioSource(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeletePortfolioSource(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TelegramServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'TelegramUser': grpc.unary_unary_rpc_method_handler(
          servicer.TelegramUser,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramUserRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramUserResponse.SerializeToString,
      ),
      'TelegramAuthExchange': grpc.unary_unary_rpc_method_handler(
          servicer.TelegramAuthExchange,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramAuthExchangeRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramAuthExchangeResponse.SerializeToString,
      ),
      'TelegramUserWallets': grpc.unary_unary_rpc_method_handler(
          servicer.TelegramUserWallets,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramUserWalletsRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramUserWalletsResponse.SerializeToString,
      ),
      'HyperliquidMostTrackedWallets': grpc.unary_unary_rpc_method_handler(
          servicer.HyperliquidMostTrackedWallets,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidMostTrackedWalletsRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidMostTrackedWalletsResponse.SerializeToString,
      ),
      'HyperliquidLaunchTrade': grpc.unary_unary_rpc_method_handler(
          servicer.HyperliquidLaunchTrade,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidLaunchTradeRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidLaunchTradeResponse.SerializeToString,
      ),
      'LaunchHyperliquidLaunch': grpc.unary_unary_rpc_method_handler(
          servicer.LaunchHyperliquidLaunch,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.LaunchHyperliquidLaunchRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.LaunchHyperliquidLaunchResponse.SerializeToString,
      ),
      'EditHyperliquidLaunch': grpc.unary_unary_rpc_method_handler(
          servicer.EditHyperliquidLaunch,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.EditHyperliquidLaunchRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.EditHyperliquidLaunchResponse.SerializeToString,
      ),
      'HpumpV1LaunchTrade': grpc.unary_unary_rpc_method_handler(
          servicer.HpumpV1LaunchTrade,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HpumpV1LaunchTradeRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HpumpV1LaunchTradeResponse.SerializeToString,
      ),
      'LaunchHpumpV1Launch': grpc.unary_unary_rpc_method_handler(
          servicer.LaunchHpumpV1Launch,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.LaunchHpumpV1LaunchRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.LaunchHpumpV1LaunchResponse.SerializeToString,
      ),
      'HyperliquidCoreAction': grpc.unary_unary_rpc_method_handler(
          servicer.HyperliquidCoreAction,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidCoreActionRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidCoreActionResponse.SerializeToString,
      ),
      'HyperliquidSpotTrade': grpc.unary_unary_rpc_method_handler(
          servicer.HyperliquidSpotTrade,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidSpotTradeRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidSpotTradeResponse.SerializeToString,
      ),
      'HyperliquidCoreTrade': grpc.unary_unary_rpc_method_handler(
          servicer.HyperliquidCoreTrade,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidCoreTradeRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidCoreTradeResponse.SerializeToString,
      ),
      'HyperliquidCoreCancelOrders': grpc.unary_unary_rpc_method_handler(
          servicer.HyperliquidCoreCancelOrders,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidCoreCancelOrdersRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidCoreCancelOrdersResponse.SerializeToString,
      ),
      'HyperliquidWalletSpotTwapSessions': grpc.unary_unary_rpc_method_handler(
          servicer.HyperliquidWalletSpotTwapSessions,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletSpotTwapSessionsRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletSpotTwapSessionsResponse.SerializeToString,
      ),
      'HyperliquidWalletTwapSessions': grpc.unary_unary_rpc_method_handler(
          servicer.HyperliquidWalletTwapSessions,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletTwapSessionsRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletTwapSessionsResponse.SerializeToString,
      ),
      'HyperliquidWalletScaleSessions': grpc.unary_unary_rpc_method_handler(
          servicer.HyperliquidWalletScaleSessions,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletScaleSessionsRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletScaleSessionsResponse.SerializeToString,
      ),
      'HyperliquidTwapCreate': grpc.unary_unary_rpc_method_handler(
          servicer.HyperliquidTwapCreate,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidTwapCreateRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidTwapCreateResponse.SerializeToString,
      ),
      'HyperliquidTwapModify': grpc.unary_unary_rpc_method_handler(
          servicer.HyperliquidTwapModify,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidTwapModifyRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidTwapModifyResponse.SerializeToString,
      ),
      'HyperliquidTwapCancel': grpc.unary_unary_rpc_method_handler(
          servicer.HyperliquidTwapCancel,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidTwapCancelRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidTwapCancelResponse.SerializeToString,
      ),
      'HyperliquidScaleCreate': grpc.unary_unary_rpc_method_handler(
          servicer.HyperliquidScaleCreate,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidScaleCreateRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidScaleCreateResponse.SerializeToString,
      ),
      'HyperliquidScaleCancel': grpc.unary_unary_rpc_method_handler(
          servicer.HyperliquidScaleCancel,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidScaleCancelRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidScaleCancelResponse.SerializeToString,
      ),
      'HyperliquidSpotSniperConfigs': grpc.unary_unary_rpc_method_handler(
          servicer.HyperliquidSpotSniperConfigs,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidSpotSniperConfigsRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidSpotSniperConfigsResponse.SerializeToString,
      ),
      'CreateHyperliquidSpotSniperConfig': grpc.unary_unary_rpc_method_handler(
          servicer.CreateHyperliquidSpotSniperConfig,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.CreateHyperliquidSpotSniperConfigRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.CreateHyperliquidSpotSniperConfigResponse.SerializeToString,
      ),
      'DeleteHyperliquidSpotSniperConfig': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteHyperliquidSpotSniperConfig,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.DeleteHyperliquidSpotSniperConfigRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.DeleteHyperliquidSpotSniperConfigResponse.SerializeToString,
      ),
      'UpdateHyperliquidSpotSniperConfig': grpc.unary_unary_rpc_method_handler(
          servicer.UpdateHyperliquidSpotSniperConfig,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.UpdateHyperliquidSpotSniperConfigRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.UpdateHyperliquidSpotSniperConfigResponse.SerializeToString,
      ),
      'HyperliquidWalletCreate': grpc.unary_unary_rpc_method_handler(
          servicer.HyperliquidWalletCreate,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletCreateRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletCreateResponse.SerializeToString,
      ),
      'HyperliquidWalletDelete': grpc.unary_unary_rpc_method_handler(
          servicer.HyperliquidWalletDelete,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletDeleteRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletDeleteResponse.SerializeToString,
      ),
      'HyperliquidWalletSetPublic': grpc.unary_unary_rpc_method_handler(
          servicer.HyperliquidWalletSetPublic,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletSetPublicRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletSetPublicResponse.SerializeToString,
      ),
      'HyperliquidAgentSignatureCreate': grpc.unary_unary_rpc_method_handler(
          servicer.HyperliquidAgentSignatureCreate,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidAgentSignatureCreateRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidAgentSignatureCreateResponse.SerializeToString,
      ),
      'HyperliquidAgentWalletCreate': grpc.unary_unary_rpc_method_handler(
          servicer.HyperliquidAgentWalletCreate,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidAgentWalletCreateRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidAgentWalletCreateResponse.SerializeToString,
      ),
      'HyperliquidWalletUpdate': grpc.unary_unary_rpc_method_handler(
          servicer.HyperliquidWalletUpdate,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletUpdateRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HyperliquidWalletUpdateResponse.SerializeToString,
      ),
      'HfunCabalAlerts': grpc.unary_stream_rpc_method_handler(
          servicer.HfunCabalAlerts,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.HfunCabalAlertsRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.HfunCabalAlertsResponse.SerializeToString,
      ),
      'TelegramChatWalletPackCreate': grpc.unary_unary_rpc_method_handler(
          servicer.TelegramChatWalletPackCreate,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramChatWalletPackCreateRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramChatWalletPackCreateResponse.SerializeToString,
      ),
      'TelegramChatWalletPackRename': grpc.unary_unary_rpc_method_handler(
          servicer.TelegramChatWalletPackRename,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramChatWalletPackRenameRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramChatWalletPackRenameResponse.SerializeToString,
      ),
      'TelegramChatWalletPackLabelAdd': grpc.unary_unary_rpc_method_handler(
          servicer.TelegramChatWalletPackLabelAdd,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramChatWalletPackLabelAddRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramChatWalletPackLabelAddResponse.SerializeToString,
      ),
      'TelegramChatWalletPackLabelModify': grpc.unary_unary_rpc_method_handler(
          servicer.TelegramChatWalletPackLabelModify,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramChatWalletPackLabelModifyRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramChatWalletPackLabelModifyResponse.SerializeToString,
      ),
      'TelegramChatWalletPackLabelRemove': grpc.unary_unary_rpc_method_handler(
          servicer.TelegramChatWalletPackLabelRemove,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramChatWalletPackLabelDeleteRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.TelegramChatWalletPackLabelDeleteResponse.SerializeToString,
      ),
      'SupportConversationStart': grpc.unary_unary_rpc_method_handler(
          servicer.SupportConversationStart,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportConversationStartRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportConversationStartResponse.SerializeToString,
      ),
      'SupportMessageSend': grpc.unary_unary_rpc_method_handler(
          servicer.SupportMessageSend,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportMessageSendRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportMessageSendResponse.SerializeToString,
      ),
      'SupportConversationHistory': grpc.unary_unary_rpc_method_handler(
          servicer.SupportConversationHistory,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportConversationHistoryRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportConversationHistoryResponse.SerializeToString,
      ),
      'SupportConversationList': grpc.unary_unary_rpc_method_handler(
          servicer.SupportConversationList,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportConversationListRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportConversationListResponse.SerializeToString,
      ),
      'SupportConversationClose': grpc.unary_unary_rpc_method_handler(
          servicer.SupportConversationClose,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportConversationCloseRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportConversationCloseResponse.SerializeToString,
      ),
      'SupportTicketStatus': grpc.unary_unary_rpc_method_handler(
          servicer.SupportTicketStatus,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportTicketStatusRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.SupportTicketStatusResponse.SerializeToString,
      ),
      'GetPortfolioAllocator': grpc.unary_unary_rpc_method_handler(
          servicer.GetPortfolioAllocator,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.GetPortfolioAllocatorRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.GetPortfolioAllocatorResponse.SerializeToString,
      ),
      'ListPortfolioAllocators': grpc.unary_unary_rpc_method_handler(
          servicer.ListPortfolioAllocators,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.ListPortfolioAllocatorsRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.ListPortfolioAllocatorsResponse.SerializeToString,
      ),
      'ListEnabledPortfolioAllocators': grpc.unary_unary_rpc_method_handler(
          servicer.ListEnabledPortfolioAllocators,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.ListEnabledPortfolioAllocatorsRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.ListEnabledPortfolioAllocatorsResponse.SerializeToString,
      ),
      'GetPortfolioSource': grpc.unary_unary_rpc_method_handler(
          servicer.GetPortfolioSource,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.GetPortfolioSourceRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.GetPortfolioSourceResponse.SerializeToString,
      ),
      'ListPortfolioSources': grpc.unary_unary_rpc_method_handler(
          servicer.ListPortfolioSources,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.ListPortfolioSourcesRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.ListPortfolioSourcesResponse.SerializeToString,
      ),
      'CreatePortfolioAllocator': grpc.unary_unary_rpc_method_handler(
          servicer.CreatePortfolioAllocator,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.CreatePortfolioAllocatorRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.CreatePortfolioAllocatorResponse.SerializeToString,
      ),
      'UpdatePortfolioAllocator': grpc.unary_unary_rpc_method_handler(
          servicer.UpdatePortfolioAllocator,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.UpdatePortfolioAllocatorRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.UpdatePortfolioAllocatorResponse.SerializeToString,
      ),
      'DeletePortfolioAllocator': grpc.unary_unary_rpc_method_handler(
          servicer.DeletePortfolioAllocator,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.DeletePortfolioAllocatorRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.DeletePortfolioAllocatorResponse.SerializeToString,
      ),
      'CreatePortfolioSource': grpc.unary_unary_rpc_method_handler(
          servicer.CreatePortfolioSource,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.CreatePortfolioSourceRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.CreatePortfolioSourceResponse.SerializeToString,
      ),
      'UpdatePortfolioSource': grpc.unary_unary_rpc_method_handler(
          servicer.UpdatePortfolioSource,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.UpdatePortfolioSourceRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.UpdatePortfolioSourceResponse.SerializeToString,
      ),
      'DeletePortfolioSource': grpc.unary_unary_rpc_method_handler(
          servicer.DeletePortfolioSource,
          request_deserializer=hypurr_dot_telegram_dot_telegram__service__pb2.DeletePortfolioSourceRequest.FromString,
          response_serializer=hypurr_dot_telegram_dot_telegram__service__pb2.DeletePortfolioSourceResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hypurr.Telegram', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
